// German Rap / Trap / Afroswing Vocabulary for Rhyme Finder
// Format: { word, phonetic, rhymeSuffix, lang, vibe }

export const GERMAN_VOCAB = [
  // ─── -eine ───────────────────────────────────────────────────────────────
  { word: "Scheine",      phonetic: "SH AY N AH",       rhymeSuffix: "eine",  lang: "de", vibe: "flex" },
  { word: "Steine",       phonetic: "SH T AY N AH",     rhymeSuffix: "eine",  lang: "de", vibe: "hard" },
  { word: "Beine",        phonetic: "B AY N AH",         rhymeSuffix: "eine",  lang: "de", vibe: "smooth" },
  { word: "meine",        phonetic: "M AY N AH",         rhymeSuffix: "eine",  lang: "de", vibe: "emotional" },
  { word: "deine",        phonetic: "D AY N AH",         rhymeSuffix: "eine",  lang: "de", vibe: "emotional" },
  { word: "seine",        phonetic: "Z AY N AH",         rhymeSuffix: "eine",  lang: "de", vibe: "street" },
  { word: "reine",        phonetic: "R AY N AH",         rhymeSuffix: "eine",  lang: "de", vibe: "melodic" },
  { word: "kleine",       phonetic: "KL AY N AH",        rhymeSuffix: "eine",  lang: "de", vibe: "light" },
  { word: "Leine",        phonetic: "L AY N AH",         rhymeSuffix: "eine",  lang: "de", vibe: "street" },
  { word: "alleine",      phonetic: "AH L AY N AH",      rhymeSuffix: "eine",  lang: "de", vibe: "emotional" },

  // ─── -ieren ───────────────────────────────────────────────────────────────
  { word: "kassieren",    phonetic: "K AH S IH R AH N",  rhymeSuffix: "ieren", lang: "de", vibe: "flex" },
  { word: "investieren",  phonetic: "IH N V EH S T IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "flex" },
  { word: "funktionieren",phonetic: "F UH NK T S Y OH N IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "trap" },
  { word: "organisieren", phonetic: "OHR G AH N IH Z IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "street" },
  { word: "regieren",     phonetic: "R EH G IH R AH N",  rhymeSuffix: "ieren", lang: "de", vibe: "hard" },
  { word: "marschieren",  phonetic: "M AHR SH IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "hard" },
  { word: "studieren",    phonetic: "SH T UH D IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "smooth" },
  { word: "trainieren",   phonetic: "T R EH N IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "hard" },
  { word: "riskieren",    phonetic: "R IH S K IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "dark" },
  { word: "probieren",    phonetic: "P R OH B IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "smooth" },
  { word: "dominieren",   phonetic: "D OH M IH N IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "hard" },
  { word: "finanzieren",  phonetic: "F IH N AHN T S IH R AH N", rhymeSuffix: "ieren", lang: "de", vibe: "flex" },

  // ─── -acht ────────────────────────────────────────────────────────────────
  { word: "Nacht",        phonetic: "N AH K T",           rhymeSuffix: "acht",  lang: "de", vibe: "dark" },
  { word: "gemacht",      phonetic: "G EH M AH K T",      rhymeSuffix: "acht",  lang: "de", vibe: "street" },
  { word: "gedacht",      phonetic: "G EH D AH K T",      rhymeSuffix: "acht",  lang: "de", vibe: "emotional" },
  { word: "gebracht",     phonetic: "G EH B R AH K T",    rhymeSuffix: "acht",  lang: "de", vibe: "hard" },
  { word: "erwacht",      phonetic: "EH R V AH K T",      rhymeSuffix: "acht",  lang: "de", vibe: "melodic" },
  { word: "lacht",        phonetic: "L AH K T",           rhymeSuffix: "acht",  lang: "de", vibe: "light" },
  { word: "macht",        phonetic: "M AH K T",           rhymeSuffix: "acht",  lang: "de", vibe: "hard" },
  { word: "kracht",       phonetic: "K R AH K T",         rhymeSuffix: "acht",  lang: "de", vibe: "hard" },
  { word: "wacht",        phonetic: "V AH K T",           rhymeSuffix: "acht",  lang: "de", vibe: "dark" },
  { word: "acht",         phonetic: "AH K T",             rhymeSuffix: "acht",  lang: "de", vibe: "trap" },

  // ─── -aum ─────────────────────────────────────────────────────────────────
  { word: "Traum",        phonetic: "T R AW M",           rhymeSuffix: "aum",   lang: "de", vibe: "melodic" },
  { word: "Raum",         phonetic: "R AW M",             rhymeSuffix: "aum",   lang: "de", vibe: "smooth" },
  { word: "Baum",         phonetic: "B AW M",             rhymeSuffix: "aum",   lang: "de", vibe: "emotional" },
  { word: "Schaum",       phonetic: "SH AW M",            rhymeSuffix: "aum",   lang: "de", vibe: "light" },
  { word: "kaum",         phonetic: "K AW M",             rhymeSuffix: "aum",   lang: "de", vibe: "emotional" },
  { word: "Saum",         phonetic: "Z AW M",             rhymeSuffix: "aum",   lang: "de", vibe: "melodic" },

  // ─── -eben ────────────────────────────────────────────────────────────────
  { word: "Leben",        phonetic: "L EH B AH N",        rhymeSuffix: "eben",  lang: "de", vibe: "emotional" },
  { word: "geben",        phonetic: "G EH B AH N",        rhymeSuffix: "eben",  lang: "de", vibe: "smooth" },
  { word: "heben",        phonetic: "H EH B AH N",        rhymeSuffix: "eben",  lang: "de", vibe: "hard" },
  { word: "schweben",     phonetic: "SH V EH B AH N",     rhymeSuffix: "eben",  lang: "de", vibe: "melodic" },
  { word: "streben",      phonetic: "SH T R EH B AH N",   rhymeSuffix: "eben",  lang: "de", vibe: "emotional" },
  { word: "neben",        phonetic: "N EH B AH N",        rhymeSuffix: "eben",  lang: "de", vibe: "smooth" },
  { word: "weben",        phonetic: "V EH B AH N",        rhymeSuffix: "eben",  lang: "de", vibe: "melodic" },
  { word: "eben",         phonetic: "EH B AH N",          rhymeSuffix: "eben",  lang: "de", vibe: "street" },

  // ─── -eit ─────────────────────────────────────────────────────────────────
  { word: "Zeit",         phonetic: "TS AY T",            rhymeSuffix: "eit",   lang: "de", vibe: "emotional" },
  { word: "weit",         phonetic: "V AY T",             rhymeSuffix: "eit",   lang: "de", vibe: "melodic" },
  { word: "Leid",         phonetic: "L AY T",             rhymeSuffix: "eid",   lang: "de", vibe: "dark" },
  { word: "Kleid",        phonetic: "KL AY T",            rhymeSuffix: "eid",   lang: "de", vibe: "flex" },
  { word: "Neid",         phonetic: "N AY T",             rhymeSuffix: "eid",   lang: "de", vibe: "dark" },
  { word: "breit",        phonetic: "B R AY T",           rhymeSuffix: "eit",   lang: "de", vibe: "smooth" },
  { word: "Streit",       phonetic: "SH T R AY T",        rhymeSuffix: "eit",   lang: "de", vibe: "hard" },
  { word: "Arbeit",       phonetic: "AHR B AY T",         rhymeSuffix: "eit",   lang: "de", vibe: "street" },
  { word: "Freiheit",     phonetic: "F R AY H AY T",      rhymeSuffix: "heit",  lang: "de", vibe: "emotional" },
  { word: "Einheit",      phonetic: "AY N H AY T",        rhymeSuffix: "heit",  lang: "de", vibe: "emotional" },

  // ─── -tion ────────────────────────────────────────────────────────────────
  { word: "Motivation",   phonetic: "M OH T IH V AH T S Y OHN", rhymeSuffix: "tion", lang: "de", vibe: "trap" },
  { word: "Situation",    phonetic: "Z IH T UH AH T S Y OHN", rhymeSuffix: "tion", lang: "de", vibe: "street" },
  { word: "Generation",   phonetic: "G EH N EH R AH T S Y OHN", rhymeSuffix: "tion", lang: "de", vibe: "hard" },
  { word: "Nation",       phonetic: "N AH T S Y OHN",     rhymeSuffix: "tion",  lang: "de", vibe: "hard" },
  { word: "Revolution",   phonetic: "R EH V OH L UH T S Y OHN", rhymeSuffix: "tion", lang: "de", vibe: "dark" },
  { word: "Evolution",    phonetic: "EH V OH L UH T S Y OHN", rhymeSuffix: "tion", lang: "de", vibe: "smooth" },
  { word: "Transformation", phonetic: "T R AHN S F OHR M AH T S Y OHN", rhymeSuffix: "tion", lang: "de", vibe: "trap" },
  { word: "Inspiration",  phonetic: "IH N S P IH R AH T S Y OHN", rhymeSuffix: "tion", lang: "de", vibe: "melodic" },
  { word: "Dedication",   phonetic: "D EH D IH K AH T S Y OHN", rhymeSuffix: "tion", lang: "de", vibe: "trap" },
  { word: "Ambition",     phonetic: "AHM B IH SH AH N",   rhymeSuffix: "tion",  lang: "de", vibe: "trap" },
  { word: "Vision",       phonetic: "V IH ZH AH N",       rhymeSuffix: "ion",   lang: "de", vibe: "melodic" },
  { word: "Mission",      phonetic: "M IH SH AH N",       rhymeSuffix: "ion",   lang: "de", vibe: "hard" },
  { word: "Passion",      phonetic: "P AH SH AH N",       rhymeSuffix: "ion",   lang: "de", vibe: "melodic" },

  // ─── Geld / Erfolg ────────────────────────────────────────────────────────
  { word: "Kohle",        phonetic: "K OH L AH",          rhymeSuffix: "ohle",  lang: "de", vibe: "flex" },
  { word: "Kasse",        phonetic: "K AH S AH",          rhymeSuffix: "asse",  lang: "de", vibe: "flex" },
  { word: "verdienen",    phonetic: "F EH R D IH N AH N", rhymeSuffix: "ienen", lang: "de", vibe: "street" },
  { word: "Millionen",    phonetic: "M IH L Y OH N AH N", rhymeSuffix: "ionen", lang: "de", vibe: "flex" },
  { word: "Reichtum",     phonetic: "R AY K T UH M",      rhymeSuffix: "tum",   lang: "de", vibe: "flex" },
  { word: "Gold",         phonetic: "G OHL T",            rhymeSuffix: "old",   lang: "de", vibe: "flex" },
  { word: "Schatz",       phonetic: "SH AH T S",          rhymeSuffix: "atz",   lang: "de", vibe: "smooth" },
  { word: "Münzen",       phonetic: "M UH N T S AH N",    rhymeSuffix: "unzen", lang: "de", vibe: "flex" },
  { word: "Papier",       phonetic: "P AH P IH R",        rhymeSuffix: "ier",   lang: "de", vibe: "flex" },
  { word: "Knete",        phonetic: "K N EH T AH",        rhymeSuffix: "ete",   lang: "de", vibe: "street" },
  { word: "Moneten",      phonetic: "M OH N EH T AH N",   rhymeSuffix: "eten",  lang: "de", vibe: "street" },
  { word: "Brötchen",     phonetic: "B R OE T KH AH N",   rhymeSuffix: "chen",  lang: "de", vibe: "light" },
  { word: "Brutto",       phonetic: "B R UH T OH",        rhymeSuffix: "utto",  lang: "de", vibe: "flex" },
  { word: "Netto",        phonetic: "N EH T OH",          rhymeSuffix: "etto",  lang: "de", vibe: "flex" },
  { word: "Bonus",        phonetic: "B OH N UH S",        rhymeSuffix: "onus",  lang: "de", vibe: "flex" },
  { word: "Penner",       phonetic: "P EH N ER",          rhymeSuffix: "enner", lang: "de", vibe: "street" },
  { word: "grüne",        phonetic: "G R UH N AH",        rhymeSuffix: "üne",   lang: "de", vibe: "flex" },

  // ─── Street / Realness ────────────────────────────────────────────────────
  { word: "Straße",       phonetic: "SH T R AH S AH",     rhymeSuffix: "aße",   lang: "de", vibe: "street" },
  { word: "Asphalt",      phonetic: "AHS F AH L T",       rhymeSuffix: "alt",   lang: "de", vibe: "street" },
  { word: "Block",        phonetic: "B L AH K",           rhymeSuffix: "ock",   lang: "de", vibe: "street" },
  { word: "Hood",         phonetic: "H UH D",             rhymeSuffix: "ood",   lang: "de", vibe: "street" },
  { word: "Kiez",         phonetic: "K IH T S",           rhymeSuffix: "iez",   lang: "de", vibe: "street" },
  { word: "Beton",        phonetic: "B EH T OHN",         rhymeSuffix: "eton",  lang: "de", vibe: "hard" },
  { word: "Dreck",        phonetic: "D R EH K",           rhymeSuffix: "eck",   lang: "de", vibe: "dark" },
  { word: "kalt",         phonetic: "K AH L T",           rhymeSuffix: "alt",   lang: "de", vibe: "dark" },
  { word: "dunkel",       phonetic: "D UH N K AH L",      rhymeSuffix: "unkel", lang: "de", vibe: "dark" },
  { word: "Licht",        phonetic: "L IH K T",           rhymeSuffix: "icht",  lang: "de", vibe: "melodic" },
  { word: "Schatten",     phonetic: "SH AH T AH N",       rhymeSuffix: "atten", lang: "de", vibe: "dark" },
  { word: "real",         phonetic: "R EH AH L",          rhymeSuffix: "eal",   lang: "de", vibe: "street" },
  { word: "echt",         phonetic: "EH K T",             rhymeSuffix: "echt",  lang: "de", vibe: "street" },
  { word: "hart",         phonetic: "H AHR T",            rhymeSuffix: "art",   lang: "de", vibe: "hard" },
  { word: "Wahrheit",     phonetic: "V AHR H AY T",       rhymeSuffix: "heit",  lang: "de", vibe: "emotional" },
  { word: "Survival",     phonetic: "S ER V AY V AH L",   rhymeSuffix: "ival",  lang: "de", vibe: "hard" },
  { word: "Gasse",        phonetic: "G AH S AH",          rhymeSuffix: "asse",  lang: "de", vibe: "street" },
  { word: "Ecke",         phonetic: "EH K AH",            rhymeSuffix: "ecke",  lang: "de", vibe: "street" },

  // ─── Lifestyle / Flex ─────────────────────────────────────────────────────
  { word: "Drip",         phonetic: "D R IH P",           rhymeSuffix: "ip",    lang: "de", vibe: "flex" },
  { word: "Wave",         phonetic: "W EY V",             rhymeSuffix: "ave",   lang: "de", vibe: "afroswing" },
  { word: "Swag",         phonetic: "S W AE G",           rhymeSuffix: "ag",    lang: "de", vibe: "flex" },
  { word: "fresh",        phonetic: "F R EH SH",          rhymeSuffix: "esh",   lang: "de", vibe: "flex" },
  { word: "clean",        phonetic: "K L IY N",           rhymeSuffix: "ean",   lang: "de", vibe: "smooth" },
  { word: "Kette",        phonetic: "K EH T AH",          rhymeSuffix: "ette",  lang: "de", vibe: "flex" },
  { word: "Ring",         phonetic: "R IH NG",            rhymeSuffix: "ing",   lang: "de", vibe: "flex" },
  { word: "Rolex",        phonetic: "R OH L EH K S",      rhymeSuffix: "olex",  lang: "de", vibe: "flex" },
  { word: "Benz",         phonetic: "B EH N T S",         rhymeSuffix: "enz",   lang: "de", vibe: "flex" },
  { word: "Beamer",       phonetic: "B IH M ER",          rhymeSuffix: "eamer", lang: "de", vibe: "flex" },
  { word: "Lambo",        phonetic: "L AE M B OH",        rhymeSuffix: "ambo",  lang: "de", vibe: "flex" },
  { word: "Porsche",      phonetic: "P OHR SH AH",        rhymeSuffix: "orsche",lang: "de", vibe: "flex" },
  { word: "Yacht",        phonetic: "Y AH T",             rhymeSuffix: "acht",  lang: "de", vibe: "flex" },
  { word: "Villa",        phonetic: "V IH L AH",          rhymeSuffix: "illa",  lang: "de", vibe: "flex" },
  { word: "Suite",        phonetic: "S W IY T",           rhymeSuffix: "uite",  lang: "de", vibe: "flex" },
  { word: "Platinum",     phonetic: "P L AE T IH N AH M", rhymeSuffix: "inum",  lang: "de", vibe: "flex" },
  { word: "VIP",          phonetic: "V IY AY P IY",       rhymeSuffix: "ip",    lang: "de", vibe: "flex" },
  { word: "Uhr",          phonetic: "UH R",               rhymeSuffix: "uhr",   lang: "de", vibe: "flex" },

  // ─── Emotions / Deep ──────────────────────────────────────────────────────
  { word: "Träume",       phonetic: "T R OY M AH",        rhymeSuffix: "äume",  lang: "de", vibe: "melodic" },
  { word: "Liebe",        phonetic: "L IH B AH",          rhymeSuffix: "iebe",  lang: "de", vibe: "emotional" },
  { word: "Schmerz",      phonetic: "SH M EH R T S",      rhymeSuffix: "erz",   lang: "de", vibe: "dark" },
  { word: "Herz",         phonetic: "H EH R T S",         rhymeSuffix: "erz",   lang: "de", vibe: "emotional" },
  { word: "allein",       phonetic: "AH L AY N",          rhymeSuffix: "ein",   lang: "de", vibe: "emotional" },
  { word: "kämpfen",      phonetic: "K EH M P F AH N",    rhymeSuffix: "ämpfen",lang: "de", vibe: "hard" },
  { word: "hoffen",       phonetic: "H AH F AH N",        rhymeSuffix: "offen", lang: "de", vibe: "emotional" },
  { word: "glauben",      phonetic: "G L AW B AH N",      rhymeSuffix: "auben", lang: "de", vibe: "emotional" },
  { word: "verloren",     phonetic: "F EH R L OH R AH N", rhymeSuffix: "oren",  lang: "de", vibe: "dark" },
  { word: "gefunden",     phonetic: "G EH F UH N D AH N", rhymeSuffix: "unden", lang: "de", vibe: "emotional" },
  { word: "stark",        phonetic: "SH T AHR K",         rhymeSuffix: "ark",   lang: "de", vibe: "hard" },
  { word: "schwach",      phonetic: "SH V AH K",          rhymeSuffix: "ach",   lang: "de", vibe: "dark" },
  { word: "Seele",        phonetic: "Z EH L AH",          rhymeSuffix: "eele",  lang: "de", vibe: "emotional" },
  { word: "Geist",        phonetic: "G AY S T",           rhymeSuffix: "eist",  lang: "de", vibe: "melodic" },
  { word: "Feuer",        phonetic: "F OY ER",            rhymeSuffix: "euer",  lang: "de", vibe: "dark" },
  { word: "Sturm",        phonetic: "SH T UH R M",        rhymeSuffix: "urm",   lang: "de", vibe: "dark" },

  // ─── Denglisch Mix ────────────────────────────────────────────────────────
  { word: "geflext",      phonetic: "G EH F L EH K S T",  rhymeSuffix: "exed",  lang: "de", vibe: "flex" },
  { word: "gevibt",       phonetic: "G EH V IH B T",      rhymeSuffix: "ibt",   lang: "de", vibe: "afroswing" },
  { word: "blessed",      phonetic: "B L EH S T",         rhymeSuffix: "essed", lang: "de", vibe: "melodic" },
  { word: "krass",        phonetic: "K R AH S",           rhymeSuffix: "ass",   lang: "de", vibe: "street" },
  { word: "moves",        phonetic: "M UH V Z",           rhymeSuffix: "oves",  lang: "de", vibe: "smooth" },
  { word: "grinden",      phonetic: "G R AY N D AH N",    rhymeSuffix: "inden", lang: "de", vibe: "trap" },
  { word: "hustlen",      phonetic: "H AH S AH L AH N",   rhymeSuffix: "ustlen",lang: "de", vibe: "trap" },
  { word: "checken",      phonetic: "T SH EH K AH N",     rhymeSuffix: "ecken", lang: "de", vibe: "street" },
  { word: "leveln",       phonetic: "L EH V AH L N",      rhymeSuffix: "eveln", lang: "de", vibe: "trap" },
  { word: "pushen",       phonetic: "P UH SH AH N",       rhymeSuffix: "ushen", lang: "de", vibe: "trap" },
  { word: "flexen",       phonetic: "F L EH K S AH N",    rhymeSuffix: "exen",  lang: "de", vibe: "flex" },
  { word: "chillen",      phonetic: "T SH IH L AH N",     rhymeSuffix: "illen", lang: "de", vibe: "smooth" },
  { word: "finessen",     phonetic: "F IH N EH S AH N",   rhymeSuffix: "essen", lang: "de", vibe: "street" },
  { word: "Connections",  phonetic: "K AH N EH K SH AH N Z", rhymeSuffix: "ions", lang: "de", vibe: "trap" },
  { word: "Network",      phonetic: "N EH T V OHR K",     rhymeSuffix: "ork",   lang: "de", vibe: "flex" },
  { word: "Business",     phonetic: "B IH Z N IH S",      rhymeSuffix: "ness",  lang: "de", vibe: "flex" },
  { word: "faden",        phonetic: "F AH D AH N",        rhymeSuffix: "aden",  lang: "de", vibe: "smooth" },
  { word: "Vibes",        phonetic: "V AY B Z",           rhymeSuffix: "ibes",  lang: "de", vibe: "afroswing" },

  // ─── German Trap Specific ─────────────────────────────────────────────────
  { word: "Bande",        phonetic: "B AH N D AH",        rhymeSuffix: "ande",  lang: "de", vibe: "trap" },
  { word: "Digga",        phonetic: "D IH G AH",          rhymeSuffix: "igga",  lang: "de", vibe: "street" },
  { word: "Wallah",       phonetic: "V AH L AH",          rhymeSuffix: "allah", lang: "de", vibe: "trap" },
  { word: "Bruder",       phonetic: "B R UH D ER",        rhymeSuffix: "uder",  lang: "de", vibe: "street" },
  { word: "Alter",        phonetic: "AH L T ER",          rhymeSuffix: "alter", lang: "de", vibe: "street" },
  { word: "Homie",        phonetic: "H OH M IY",          rhymeSuffix: "omie",  lang: "de", vibe: "smooth" },
  { word: "Gang",         phonetic: "G AE NG",            rhymeSuffix: "ang",   lang: "de", vibe: "trap" },
  { word: "Crew",         phonetic: "K R UW",             rhymeSuffix: "ew",    lang: "de", vibe: "trap" },
  { word: "Squad",        phonetic: "S K W AH D",         rhymeSuffix: "uad",   lang: "de", vibe: "trap" },
  { word: "Bratan",       phonetic: "B R AH T AH N",      rhymeSuffix: "atan",  lang: "de", vibe: "trap" },
  { word: "Habibi",       phonetic: "H AH B IH B IY",     rhymeSuffix: "ibi",   lang: "de", vibe: "afroswing" },
  { word: "lan",          phonetic: "L AH N",             rhymeSuffix: "an",    lang: "de", vibe: "trap" },
  { word: "Ey",           phonetic: "EY",                 rhymeSuffix: "ey",    lang: "de", vibe: "street" },
  { word: "aight",        phonetic: "AY T",               rhymeSuffix: "ight",  lang: "de", vibe: "smooth" },
  { word: "jo",           phonetic: "Y OH",               rhymeSuffix: "jo",    lang: "de", vibe: "light" },
  { word: "ne",           phonetic: "N EH",               rhymeSuffix: "ne",    lang: "de", vibe: "street" },
  { word: "Team",         phonetic: "T IY M",             rhymeSuffix: "eam",   lang: "de", vibe: "trap" },

  // ─── Verben / Actions ─────────────────────────────────────────────────────
  { word: "feiern",       phonetic: "F AY ER N",          rhymeSuffix: "eiern", lang: "de", vibe: "light" },
  { word: "spielen",      phonetic: "SH P IH L AH N",     rhymeSuffix: "ielen", lang: "de", vibe: "smooth" },
  { word: "siegen",       phonetic: "Z IH G AH N",        rhymeSuffix: "iegen", lang: "de", vibe: "hard" },
  { word: "laufen",       phonetic: "L AW F AH N",        rhymeSuffix: "aufen", lang: "de", vibe: "street" },
  { word: "rennen",       phonetic: "R EH N AH N",        rhymeSuffix: "ennen", lang: "de", vibe: "hard" },
  { word: "fliegen",      phonetic: "F L IH G AH N",      rhymeSuffix: "iegen", lang: "de", vibe: "melodic" },
  { word: "brennen",      phonetic: "B R EH N AH N",      rhymeSuffix: "ennen", lang: "de", vibe: "dark" },
  { word: "kennen",       phonetic: "K EH N AH N",        rhymeSuffix: "ennen", lang: "de", vibe: "street" },
  { word: "können",       phonetic: "K OE N AH N",        rhymeSuffix: "önnen", lang: "de", vibe: "smooth" },
  { word: "gewinnen",     phonetic: "G EH V IH N AH N",   rhymeSuffix: "innen", lang: "de", vibe: "hard" },

  // ─── Abstract / Motivation ────────────────────────────────────────────────
  { word: "Ziel",         phonetic: "T S IH L",           rhymeSuffix: "iel",   lang: "de", vibe: "emotional" },
  { word: "Wille",        phonetic: "V IH L AH",          rhymeSuffix: "ille",  lang: "de", vibe: "hard" },
  { word: "Kraft",        phonetic: "K R AH F T",         rhymeSuffix: "aft",   lang: "de", vibe: "hard" },
  { word: "Energie",      phonetic: "EH N ER G IH",       rhymeSuffix: "ergie", lang: "de", vibe: "trap" },
  { word: "Fokus",        phonetic: "F OH K UH S",        rhymeSuffix: "okus",  lang: "de", vibe: "trap" },
  { word: "Disziplin",    phonetic: "D IH S TS IH P L IH N", rhymeSuffix: "lin",lang: "de", vibe: "hard" },
  { word: "Erfolg",       phonetic: "EH R F OHL K",       rhymeSuffix: "olg",   lang: "de", vibe: "flex" },
  { word: "Hunger",       phonetic: "H UH NG ER",         rhymeSuffix: "unger", lang: "de", vibe: "trap" },
  { word: "Ausdauer",     phonetic: "AW S D AW ER",       rhymeSuffix: "auer",  lang: "de", vibe: "emotional" },
  { word: "Vertrauen",    phonetic: "F EH R T R AW AH N", rhymeSuffix: "auen",  lang: "de", vibe: "emotional" },

  // ─── Natur / Metaphern ────────────────────────────────────────────────────
  { word: "Regen",        phonetic: "R EH G AH N",        rhymeSuffix: "egen",  lang: "de", vibe: "melodic" },
  { word: "Wind",         phonetic: "V IH N T",           rhymeSuffix: "ind",   lang: "de", vibe: "melodic" },
  { word: "Wasser",       phonetic: "V AH S ER",          rhymeSuffix: "asser", lang: "de", vibe: "smooth" },
  { word: "Stein",        phonetic: "SH T AY N",          rhymeSuffix: "ein",   lang: "de", vibe: "hard" },
  { word: "Berg",         phonetic: "B EH R K",           rhymeSuffix: "erg",   lang: "de", vibe: "hard" },
  { word: "Tal",          phonetic: "T AH L",             rhymeSuffix: "al",    lang: "de", vibe: "melodic" },
  { word: "Sonne",        phonetic: "Z AH N AH",          rhymeSuffix: "onne",  lang: "de", vibe: "afroswing" },
  { word: "Mond",         phonetic: "M OHN T",            rhymeSuffix: "ond",   lang: "de", vibe: "melodic" },
  { word: "Stern",        phonetic: "SH T EH R N",        rhymeSuffix: "ern",   lang: "de", vibe: "melodic" },
  { word: "Himmel",       phonetic: "H IH M AH L",        rhymeSuffix: "immel", lang: "de", vibe: "emotional" },
  { word: "Erde",         phonetic: "EH R D AH",          rhymeSuffix: "erde",  lang: "de", vibe: "street" },
  { word: "Wurzeln",      phonetic: "V UHR T S AH L N",   rhymeSuffix: "urzeln",lang: "de", vibe: "emotional" },
  { word: "Wellen",       phonetic: "V EH L AH N",        rhymeSuffix: "ellen", lang: "de", vibe: "afroswing" },
  { word: "Fluss",        phonetic: "F L UH S",           rhymeSuffix: "uss",   lang: "de", vibe: "smooth" },
  { word: "Meer",         phonetic: "M EH R",             rhymeSuffix: "eer",   lang: "de", vibe: "afroswing" },
  { word: "Ozean",        phonetic: "OH T S EH AH N",     rhymeSuffix: "ean",   lang: "de", vibe: "afroswing" },
  { word: "Äste",         phonetic: "EH S T AH",          rhymeSuffix: "äste",  lang: "de", vibe: "emotional" },

  // ─── Zeit ─────────────────────────────────────────────────────────────────
  { word: "Morgen",       phonetic: "M OHR G AH N",       rhymeSuffix: "orgen", lang: "de", vibe: "emotional" },
  { word: "Abend",        phonetic: "AH B AH N T",        rhymeSuffix: "abend", lang: "de", vibe: "dark" },
  { word: "heute",        phonetic: "H OY T AH",          rhymeSuffix: "eute",  lang: "de", vibe: "street" },
  { word: "gestern",      phonetic: "G EH S T EH R N",    rhymeSuffix: "estern",lang: "de", vibe: "emotional" },
  { word: "immer",        phonetic: "IH M ER",            rhymeSuffix: "immer", lang: "de", vibe: "emotional" },
  { word: "niemals",      phonetic: "N IH M AH L S",      rhymeSuffix: "emals", lang: "de", vibe: "dark" },
  { word: "jetzt",        phonetic: "Y EH T S T",         rhymeSuffix: "etzt",  lang: "de", vibe: "trap" },
  { word: "Moment",       phonetic: "M OH M EH N T",      rhymeSuffix: "ment",  lang: "de", vibe: "smooth" },
  { word: "Stunde",       phonetic: "SH T UH N D AH",     rhymeSuffix: "unde",  lang: "de", vibe: "emotional" },
  { word: "Minute",       phonetic: "M IH N UH T AH",     rhymeSuffix: "inute", lang: "de", vibe: "smooth" },
  { word: "Jahr",         phonetic: "Y AHR",              rhymeSuffix: "ahr",   lang: "de", vibe: "emotional" },
  { word: "Ewigkeit",     phonetic: "EH V IH K AY T",     rhymeSuffix: "keit",  lang: "de", vibe: "melodic" },
  { word: "Vergangenheit",phonetic: "F EH R G AH NG AH N H AY T", rhymeSuffix: "heit", lang: "de", vibe: "emotional" },
  { word: "Zukunft",      phonetic: "T S UH K UH N F T",  rhymeSuffix: "unft",  lang: "de", vibe: "melodic" },
  { word: "Tag",          phonetic: "T AH K",             rhymeSuffix: "ag",    lang: "de", vibe: "street" },

  // ─── Afroswing specific ───────────────────────────────────────────────────
  { word: "Baby",         phonetic: "B EY B IY",          rhymeSuffix: "aby",   lang: "de", vibe: "afroswing" },
  { word: "Melodie",      phonetic: "M EH L OH D IH",     rhymeSuffix: "odie",  lang: "de", vibe: "melodic" },
  { word: "Rhythmus",     phonetic: "R IH T M UH S",      rhymeSuffix: "hmus",  lang: "de", vibe: "afroswing" },
  { word: "tanzen",       phonetic: "T AH N T S AH N",    rhymeSuffix: "anzen", lang: "de", vibe: "afroswing" },
  { word: "singen",       phonetic: "Z IH NG AH N",       rhymeSuffix: "ingen", lang: "de", vibe: "melodic" },
  { word: "fühlen",       phonetic: "F UH L AH N",        rhymeSuffix: "ühlen", lang: "de", vibe: "melodic" },
  { word: "spüren",       phonetic: "SH P UH R AH N",     rhymeSuffix: "üren",  lang: "de", vibe: "melodic" },
  { word: "träumen",      phonetic: "T R OY M AH N",      rhymeSuffix: "äumen", lang: "de", vibe: "melodic" },
  { word: "Groove",       phonetic: "G R UH V",           rhymeSuffix: "oove",  lang: "de", vibe: "afroswing" },
  { word: "Flow",         phonetic: "F L OH",             rhymeSuffix: "low",   lang: "de", vibe: "smooth" },

  // ─── Extra Hard/Trap ──────────────────────────────────────────────────────
  { word: "Messer",       phonetic: "M EH S ER",          rhymeSuffix: "esser", lang: "de", vibe: "dark" },
  { word: "Kugel",        phonetic: "K UH G AH L",        rhymeSuffix: "ugel",  lang: "de", vibe: "dark" },
  { word: "Krieg",        phonetic: "K R IH K",           rhymeSuffix: "ieg",   lang: "de", vibe: "hard" },
  { word: "Feind",        phonetic: "F AY N T",           rhymeSuffix: "eind",  lang: "de", vibe: "dark" },
  { word: "Blut",         phonetic: "B L UH T",           rhymeSuffix: "ut",    lang: "de", vibe: "dark" },
  { word: "Narbe",        phonetic: "N AHR B AH",         rhymeSuffix: "arbe",  lang: "de", vibe: "dark" },
  { word: "Wunde",        phonetic: "V UH N D AH",        rhymeSuffix: "unde",  lang: "de", vibe: "dark" },
  { word: "Kampf",        phonetic: "K AH M P F",         rhymeSuffix: "ampf",  lang: "de", vibe: "hard" },
  { word: "Angriff",      phonetic: "AH N G R IH F",      rhymeSuffix: "riff",  lang: "de", vibe: "hard" },
  { word: "Macht",        phonetic: "M AH K T",           rhymeSuffix: "acht",  lang: "de", vibe: "hard" },
  { word: "Kontrolle",    phonetic: "K AH N T R OH L AH", rhymeSuffix: "olle",  lang: "de", vibe: "hard" },
  { word: "System",       phonetic: "Z IH S T EH M",      rhymeSuffix: "stem",  lang: "de", vibe: "street" },
  { word: "Lüge",         phonetic: "L UH G AH",          rhymeSuffix: "üge",   lang: "de", vibe: "dark" },
  { word: "Verrat",       phonetic: "F EH R R AH T",      rhymeSuffix: "at",    lang: "de", vibe: "dark" },
  { word: "Rache",        phonetic: "R AH K AH",          rhymeSuffix: "ache",  lang: "de", vibe: "dark" },

  // ─── More Street Slang ────────────────────────────────────────────────────
  { word: "Mudda",        phonetic: "M UH D AH",          rhymeSuffix: "udda",  lang: "de", vibe: "street" },
  { word: "Opfer",        phonetic: "AH P F ER",          rhymeSuffix: "opfer", lang: "de", vibe: "street" },
  { word: "Bars",         phonetic: "B AHR Z",            rhymeSuffix: "ars",   lang: "de", vibe: "trap" },
  { word: "Beef",         phonetic: "B IY F",             rhymeSuffix: "eef",   lang: "de", vibe: "street" },
  { word: "diss",         phonetic: "D IH S",             rhymeSuffix: "iss",   lang: "de", vibe: "street" },
  { word: "Hype",         phonetic: "H AY P",             rhymeSuffix: "ype",   lang: "de", vibe: "trap" },
  { word: "Trap",         phonetic: "T R AE P",           rhymeSuffix: "ap",    lang: "de", vibe: "trap" },
  { word: "Beat",         phonetic: "B IY T",             rhymeSuffix: "eat",   lang: "de", vibe: "trap" },
  { word: "Mic",          phonetic: "M AY K",             rhymeSuffix: "ic",    lang: "de", vibe: "street" },
  { word: "Reim",         phonetic: "R AY M",             rhymeSuffix: "eim",   lang: "de", vibe: "street" },
  { word: "Strophe",      phonetic: "SH T R OH F AH",     rhymeSuffix: "ophe",  lang: "de", vibe: "street" },
  { word: "Refrain",      phonetic: "R EH F R EY N",      rhymeSuffix: "ain",   lang: "de", vibe: "melodic" },
  { word: "Hook",         phonetic: "H UH K",             rhymeSuffix: "ook",   lang: "de", vibe: "afroswing" },
  { word: "Track",        phonetic: "T R AE K",           rhymeSuffix: "ack",   lang: "de", vibe: "trap" },
  { word: "Album",        phonetic: "AH L B UH M",        rhymeSuffix: "bum",   lang: "de", vibe: "flex" },

  // ─── Positive/Light ───────────────────────────────────────────────────────
  { word: "Lachen",       phonetic: "L AH K AH N",        rhymeSuffix: "achen", lang: "de", vibe: "light" },
  { word: "Freude",       phonetic: "F R OY D AH",        rhymeSuffix: "eude",  lang: "de", vibe: "light" },
  { word: "Glück",        phonetic: "G L UH K",           rhymeSuffix: "ück",   lang: "de", vibe: "light" },
  { word: "Segen",        phonetic: "Z EH G AH N",        rhymeSuffix: "egen",  lang: "de", vibe: "melodic" },
  { word: "Frieden",      phonetic: "F R IH D AH N",      rhymeSuffix: "ieden", lang: "de", vibe: "light" },
  { word: "Hoffnung",     phonetic: "H AH F N UH NG",     rhymeSuffix: "nung",  lang: "de", vibe: "emotional" },
  { word: "Dankbar",      phonetic: "D AH NK B AHR",      rhymeSuffix: "bar",   lang: "de", vibe: "emotional" },
  { word: "frei",         phonetic: "F R AY",             rhymeSuffix: "ei",    lang: "de", vibe: "emotional" },
  { word: "zusammen",     phonetic: "T S UH Z AH M AH N", rhymeSuffix: "ammen", lang: "de", vibe: "emotional" },
  { word: "gemeinsam",    phonetic: "G EH M AY N Z AH M", rhymeSuffix: "sam",   lang: "de", vibe: "emotional" },
];
