// Genre guide: the quick "cheat sheet" for every sound the app can order.
// Counting is always in 4/4. "Half-Time" = at 140 BPM the snare on beat 3
// feels like 2 & 4 at 70 BPM – standard for trap/drill-type beats.
//
// fam   – family for the lexicon (US, UK, Afro, Dancehall, FR/ES, Andere)
// bpm   – typical range, keys – common keys
// inst  – typical sounds/instruments (the app picks 1–2 as "Pflicht-Sounds")
// snare, hats, bass – where things sit in the groove
// arr   – arrangement, switches, transitions
// tip   – the one thing that makes it sound like the genre
// refs  – reference artists/producers

export const FAMILIES = ['UK', 'Afro', 'Dancehall', 'US', 'FR/ES', 'Andere'];

export const GENRES = {
  // ── UK ────────────────────────────────────────────────────────────────
  'UK Afroswing': { fam: 'UK', bpm: [98, 110], keys: ['A Moll', 'F# Moll', 'C Moll', 'G Moll'],
    inst: ['Shaker & Congas', 'gezupfte Gitarre', 'warme Keys/Rhodes', 'Marimba/Kalimba', 'Dancehall-Rimshot', 'Vocal-Chops', 'runder Sub-Bass', 'Pan-Flöte'],
    snare: 'Snare/Clap auf der 3 (kommt aus dem Afrobeats, Half-Time-Feel), dazu synkopierte Rims im Dancehall-Feel (3+3+2)',
    hats: 'Shaker in 16teln, Hats leicht geshuffelt – bewusst etwas neben dem Raster',
    bass: 'runder Sub oder kurze 808, spielt eine eigene kleine Melodie',
    arr: 'Hook sehr früh (oft nach 4 Takten Intro), 16er-Parts, 8er-Hook; Drops durch kurzes Rausnehmen der Drums',
    tip: 'Groove vor allem: Percs von Hand einspielen oder leicht verschieben, viel Platz für Melodie-Vocals.',
    refs: ['J Hus', 'JAE5 (Prod.)', 'Kojo Funds', 'NSG', 'WSTRN', 'Keeya Keys', 'Blairy Hendrix (Prod.)', 'Joshua Beatz (Prod.)'],
    listen: ['WSTRN – „In2“ (2015)', 'Kojo Funds ft. Abra Cadabra – „Dun Talkin’“ (2016)', 'J Hus – „Did You See“ (2017, Prod. JAE5)', 'NSG ft. Tion Wayne – „Options“ (2018)'] },
  'UK Rap': { fam: 'UK', bpm: [136, 146], keys: ['C Moll', 'F Moll', 'G# Moll'],
    inst: ['Soul-/Piano-Sample', 'dunkle Strings', 'Chor-Pad', 'Glocken', 'harte 808', 'Vocal-Chop', 'Gitarren-Loop'],
    snare: 'auf der 3 (Half-Time)', hats: '8tel/16tel, gelegentliche Triolen-Rolls – eher zurückhaltend',
    bass: '808 folgt der Kick, eher kurz und druckvoll', arr: 'Bars im Vordergrund: Beat bleibt simpel, Beat-Switch nach dem 2. Part ist beliebt',
    tip: 'Das Sample muss Seele haben – der Beat ist die Bühne für die Bars, nicht umgekehrt.', refs: ['Skeete', 'Nines', 'Gola Gianni', 'Chip', 'Pa Salieu'] },
  'UK Sample-Rap': { fam: 'UK', bpm: [136, 146], keys: ['je nach Sample'],
    inst: ['markantes Sample (Soul, Oldie, Film, Vocal)', 'harte 808', 'UK-Drums', 'Vocal-Chop aus dem Sample', 'dezente Strings'],
    snare: 'auf der 3 (Half-Time)', hats: 'eher simpel – das Sample führt', bass: '808 folgt dem Sample-Grundton',
    arr: 'Sample als Intro alleine, dann Drums droppen; Sample-Chop als Hook', tip: 'Such ein Sample mit Charakter und bau ALLES drumherum – Nines-Style.',
    refs: ['Nines', 'Knucks', 'Skeete'] },
  'UK Drill': { fam: 'UK', bpm: [138, 144], keys: ['F# Moll', 'D Moll', 'C# Moll'],
    inst: ['Sliding 808', 'dunkle Strings', 'Choir-Pad', 'Glocken/Bells', 'Piano', 'Percs (Rim, Snaps)'],
    snare: 'Takt 1 auf der 3, Takt 2 auf der 4 (statt der 3) – das typische Drill-Stolpern; leise Ghost-Snares dazwischen', hats: 'Tresillo-Muster (3+3+2) mit Triolen-Rolls und kleinen Pausen',
    bass: '808-Slides (Porta) sind DAS Markenzeichen: kurze, schnelle Slides, meist um eine kleine Terz oder Quarte, 2–3 pro 4 Takte', arr: '16er-Parts, 808-Pattern wechselt zwischen Hook und Part',
    tip: 'Kick und 808 sind oft dasselbe – die Slides tragen die Melodie.', refs: ['Headie One', 'Digga D', 'Skeete', 'M Huncho'] },
  'UK R&B': { fam: 'UK', bpm: [95, 118], keys: ['Ab Dur', 'F Moll', 'Eb Dur'],
    inst: ['Rhodes', 'Afro-Percs', 'weiche Pads', 'gepitchte Vocal-Chops', 'Gitarre', 'Sub-Bass'],
    snare: 'Clap/Snare auf 2 & 4, oft mit Afro-Rim dazwischen', hats: 'lockere 16tel-Hats, Shaker', bass: 'warmer Sub, folgt den Akkorden',
    arr: 'Verse – Pre-Hook – Hook; Pre-Hook baut Spannung durch Filter/weniger Drums', tip: 'Akkorde mit 7ern und 9ern, alles weich und luftig.', refs: ['8synatra', 'Jorja Smith', 'Cleo Sol'] },
  'UK Garage': { fam: 'UK', bpm: [130, 136], keys: ['F Moll', 'A Moll'],
    inst: ['2-Step-Drums', 'Organ-Bass', 'gepitchte Vocal-Chops', 'Stabs', 'Plucks'], snare: 'auf 2 & 4', hats: 'stark geshuffelte Hats (Swing ~60 %)',
    bass: 'wobbliger Organ-/Reese-Bass', arr: 'Kick nicht auf jedem Schlag: 1 und „3-und“ (2-Step)', tip: 'Der Shuffle ist alles – ohne Swing klingt es nach House.', refs: ['Craig David', 'Conducta', 'Sammy Virji'] },
  'Grime': { fam: 'UK', bpm: [138, 142], keys: ['E Moll', 'D Moll'],
    inst: ['Square-Leads', 'Eski-Clicks', 'Sub-Bass', 'Stabs', 'Sirenen'], snare: 'auf der 3 (Half-Time) oder hart auf 2 & 4', hats: 'sparsam, oft gar keine',
    bass: 'dicker Sub, sehr einfach', arr: 'Kurze Loops, 8er-Blocks für Bars', tip: 'Kalt, eckig, minimal – die Energie kommt vom MC.', refs: ['Skepta', 'Wiley', 'Chip'] },
  // ── AFRO ──────────────────────────────────────────────────────────────
  'Afrobeats': { fam: 'Afro', bpm: [100, 115], keys: ['A Moll', 'G Dur', 'E Moll'],
    inst: ['Shaker', 'Congas/Talking Drum', 'melodischer Bass', 'Gitarre', 'Marimba', 'Saxophon', 'Pads'],
    snare: 'Rim/Snare synkopiert (nicht stumpf auf 2 & 4), oft auf „2-und“ und 4', hats: 'Shaker in 16teln, offene Hat auf dem Offbeat',
    bass: 'melodischer Bass, oft im Wechselspiel mit der Kick', arr: 'Lange, gleichbleibende Grooves; Variation über Percs statt über Drops',
    tip: 'Percussion-Layering: 3–4 Percs, jede mit eigenem Rhythmus.', refs: ['Tera Kòrá', 'Yung D3mz', 'Skiibii', 'Rema', 'Burna Boy'] },
  'Amapiano': { fam: 'Afro', bpm: [108, 115], keys: ['A Moll', 'D Moll', 'F Dur'],
    inst: ['Log Drum', 'Shaker', 'jazzige Piano-Chords', 'weite Pads', 'Whistle', 'Vocal-Chops', 'Saxophon'],
    snare: 'Kick 4-on-the-floor, Rim/Clap sparsam auf 2 & 4', hats: 'Shaker in 16teln (zweiter Shaker leicht versetzt), offene Hats auf dem Offbeat', bass: 'Log Drum = Bass + Percussion, rutscht in der Tonhöhe',
    arr: 'Sehr lang (5–7 Min.), baut über Filter und neue Log-Drum-Pattern', tip: 'Die Log Drum ist das Herz – spiel mit Pitch und Rhythmus.', refs: ['Kabza De Small', 'Tyla', 'Uncle Waffles'] },
  // ── DANCEHALL ─────────────────────────────────────────────────────────
  'Dancehall': { fam: 'Dancehall', bpm: [90, 110], keys: ['G Moll', 'D Moll', 'A Moll'],
    inst: ['Riddim-Drums', 'Skank-Gitarre', 'Horns/Brass', 'Organ-Stabs', 'Sub-Bass', 'Airhorn-FX'],
    snare: 'Dembow: Snare auf „1-a“ und „2-und“ (3+3+2), Kick oft auf allen 4 Schlägen', hats: 'wenig Hats, dafür Rims/Percs',
    bass: 'tiefer Sub, simple Figur',
    arr: '2–3 Sektionen: Instrumente fallen raus und kommen zurück (Dub-Prinzip), Stop-Time-Pausen vor der Hook. Verse 8 oder 16 Takte.',
    tip: 'Der 3+3+2-Rhythmus ist die DNA – alles andere darf schlicht sein. Vocals: Verse auf 1–2 Tönen, Refrain melodisch und von einem Synth gedoppelt.',
    refs: ['Skillibeng', 'Popcaan', 'Vybz Kartel'],
    listen: ['Diwali Riddim (Lenky, 2002 – Sean Paul „Get Busy“)', 'Sleng Teng (King Jammy, 1985 – komplett digital)', 'Bam Bam (Chaka Demus & Pliers „Murder She Wrote“)', 'Real Rock (Studio One, 1967)'] },
  'Dancehall-Trap': { fam: 'Dancehall', bpm: [140, 150], keys: ['F Moll', 'G Moll'],
    inst: ['Trap-808', 'Dancehall-Snare-Rolls', 'dunkle Synths', 'Airhorn', 'Percs', 'Sirene'], snare: 'Trap-Snare auf der 3 + Dancehall-Snare-Figuren dazwischen',
    hats: 'Trap-Hats mit Rolls', bass: 'lange 808 mit Glides', arr: 'Hook-lastig, harte Drops nach Pausen', tip: 'Trap-Drums + Dancehall-Swing in den Percs = der Sound.', refs: ['Skillibeng', 'Masicka', 'Intence'], listen: ['Diwali Riddim (die Clap-Figur)', 'Sleng Teng (digitaler Bass)'] },
  'Afro-Dancehall': { fam: 'Dancehall', bpm: [95, 106], keys: ['G Moll', 'D Moll', 'A Moll'],
    inst: ['Dembow-Drums', 'Afro-Percs', 'Plucks/Marimba', 'Stabs', 'tiefer Sub', 'Gitarre'], snare: 'Dembow-Pattern (3+3+2) mit Afro-Rims',
    hats: 'Shaker + wenige Hats', bass: 'Sub folgt der Kick', arr: 'Hook früh, Breaks mit nur Percs', tip: 'Zwei Welten mischen: Dembow-Snare + Afro-Shaker.', refs: ['Skillibeng', 'Juls (Prod.)', 'Projexx', 'Valiant'] },
  'Reggaeton': { fam: 'Dancehall', bpm: [88, 100], keys: ['A Moll', 'D Moll', 'F# Moll'],
    inst: ['Dembow-Drums', 'Plucks', 'Pads', 'Gitarre', '808/Sub', 'Vocal-Chops'], snare: 'Dembow: „1-a“ und „2-und“, jeden Takt gleich',
    hats: 'wenig, eher Percs', bass: '808/Sub auf der Kick', arr: 'Intro – Hook – Verse – Hook, klarer Pop-Aufbau', tip: 'Dembow durchziehen, Melodie simpel und catchy halten.', refs: ['Bad Bunny', 'Feid', 'Rauw Alejandro'] },
  // ── US: TRAP-FAMILIE ──────────────────────────────────────────────────
  'Atlanta Trap': { fam: 'US', bpm: [130, 150], keys: ['C# Moll', 'F Moll', 'A Moll'],
    inst: ['Glocken/Bells', 'Flöte', 'Piano', 'Strings', 'lange 808', 'Brass-Stabs', 'Synth-Pad'],
    snare: 'Clap/Snare auf der 3 (Half-Time)', hats: '8tel/16tel mit 1/32- und Triolen-Rolls', bass: 'lange, gestimmte 808 mit Glides',
    arr: '8er-Intro (Melodie alleine), 16er-Parts, Hook 8; Drops durch Mute vor der Hook', tip: 'Hi-Hat-Rolls und 808-Glides sind der Wiedererkennungswert (Atlanta-Style).', refs: ['Metro Boomin', 'Future', 'Southside', 'Zaytoven'] },
  'Dark Trap': { fam: 'US', bpm: [140, 160], keys: ['C Moll', 'F# Moll'],
    inst: ['Horror-Piano', 'Chor', 'orchestrale Strings', 'Glocken', 'verzerrte 808', 'Reverse-FX'], snare: 'auf der 3 (Half-Time)',
    hats: 'sparsam, gezielte Rolls', bass: 'lange 808, gern leicht verzerrt', arr: 'Spannung über Stille und plötzliche Drops', tip: 'Weniger Noten, mehr Atmosphäre – Moll und Halbtöne.', refs: ['21 Savage', 'Metro Boomin', 'Travis Scott'] },
  'Melodic Trap': { fam: 'US', bpm: [130, 150], keys: ['A Moll', 'E Moll', 'C Dur'],
    inst: ['Gitarren-Loop', 'Piano', 'Pads', 'Plucks', '808', 'Vocal-Chops'], snare: 'auf der 3 (Half-Time)', hats: 'flüssige 16tel, wenige Rolls',
    bass: '808 folgt den Akkorden', arr: 'Emotionaler Loop, Hook-lastig', tip: 'Ein starker emotionaler Loop reicht – nicht überladen.', refs: ['Lil Baby', 'Gunna', 'Wheezy', 'Polo G'] },
  'Rage': { fam: 'US', bpm: [150, 165], keys: ['C# Moll', 'F Moll'],
    inst: ['verzerrte Supersaw-Leads', 'harte 808', 'Sirenen-FX', 'Arp-Synths', 'Noise-Risers'], snare: 'auf der 3 (Half-Time), sehr hart',
    hats: 'schnelle Rolls', bass: 'übersteuerte 808', arr: 'Energie konstant hoch, Drops mit Filter-Sweeps', tip: 'Synth durch Distortion + viel Reverb = der Rage-Sound.', refs: ['Playboi Carti', 'Yeat', 'Ken Carson', 'F1lthy (Prod.)'] },
  'Plugg': { fam: 'US', bpm: [140, 160], keys: ['Db Dur', 'F Moll'],
    inst: ['verträumte Synth-Chords', 'Plugg-808', 'Glocken', 'Bell-Plucks', 'weiche Pads'], snare: 'Clap auf der 3 (Half-Time)',
    hats: 'wenige Hats, viel Platz', bass: 'lange 808, glatt', arr: 'Kurzer Loop, kaum Variation', tip: 'Minimalismus: 2–3 Elemente, verträumte Akkorde.', refs: ['Summrs', 'Autumn!', 'MexikoDro (Prod.)'] },
  'Pluggnb': { fam: 'US', bpm: [140, 155], keys: ['Eb Dur', 'Bb Moll'],
    inst: ['R&B-Akkorde (7th/9th)', 'weiche Synths', '808', 'Vocal-Chops', 'Glocken'], snare: 'Clap auf der 3 (Half-Time)',
    hats: 'sanfte Rolls', bass: 'weiche 808', arr: 'Loop mit Akkordwechsel pro Takt', tip: 'Plugg-Drums + R&B-Harmonien – romantisch und verträumt.', refs: ['Summrs', 'Autumn!'] },
  'R&B Trap': { fam: 'US', bpm: [130, 150], keys: ['Eb Dur', 'C Moll', 'Ab Dur'],
    inst: ['R&B-Akkorde (Rhodes/Pads)', 'weiche 808', 'gepitchte Vocal-Chops', 'Trap-Hats (sanft)', 'Gitarre'], snare: 'auf der 3 (Half-Time), oft Snaps/Rim',
    hats: 'sanfte Rolls', bass: '808 folgt den Akkorden', arr: 'Verse – Hook – Verse – Bridge', tip: 'Trap-Drums, aber alles weich: R&B-Harmonien führen.',
    refs: ['Summer Walker', '6LACK', 'Jhené Aiko'] },
  'Alternative R&B': { fam: 'US', bpm: [60, 90], keys: ['Db Dur', 'F Moll', 'B Moll'],
    inst: ['analoge Synths', 'verwaschene Gitarre', 'Tape-Sättigung', 'minimale Drums', 'gepitchte Vocals'], snare: 'sparsam auf 2 & 4 oder ganz ohne',
    hats: 'kaum', bass: 'warmer Synth-Bass', arr: 'Freie Songstruktur, Beat-Switches erlaubt', tip: 'Raum und Atmosphäre > Drums. Ungewöhnliche Sounds sind erwünscht.',
    refs: ['Frank Ocean', 'Brent Faiyaz', 'Daniel Caesar'] },
  '90s R&B': { fam: 'US', bpm: [90, 110], keys: ['F Moll', 'Bb Dur'],
    inst: ['New-Jack-Swing-Drums', 'Synth-Brass', 'E-Piano', 'Slap-Bass', 'Chor-Vocals'], snare: 'harte Snare auf 2 & 4',
    hats: 'geswingte 16tel (New Jack Swing)', bass: 'funky Synth-/Slap-Bass', arr: 'Klassisch: Verse – Pre – Hook – Bridge – Key-Change', tip: 'Swing in den Hats + harte Snare = sofort 90s.',
    refs: ['Blackstreet', 'Teddy Riley (Prod.)', 'SWV'] },
  'Sexy Drill': { fam: 'US', bpm: [140, 148], keys: ['je nach Sample'],
    inst: ['gepitchtes R&B-/Love-Song-Sample', 'Sliding 808', 'Drill-Hats', 'Jersey-Kicks'], snare: 'auf der 3 (Drill)',
    hats: 'Drill-Triolen', bass: '808-Slides', arr: 'Das Sample ist die Hook, Vocals eher melodisch', tip: 'Drill-Drums unter einem romantischen Sample – Bronx-Style.',
    refs: ['Cash Cobain', 'Chow Lee'] },
  'Trap Soul': { fam: 'US', bpm: [130, 150], keys: ['Ab Dur', 'F Moll'],
    inst: ['Rhodes', 'Soul-Sample', '808', 'Pads', 'Vocal-Chops'], snare: 'auf der 3 (Half-Time), oft Rim statt Snare',
    hats: 'langsame, weiche Hats', bass: '808 dezent', arr: 'Verse/Hook ruhig, viel Raum', tip: 'R&B-Gefühl mit Trap-Drums – leise und intim.', refs: ['Bryson Tiller', 'PARTYNEXTDOOR'] },
  'Detroit': { fam: 'US', bpm: [94, 104], bpmNote: 'im FL-Projekt oft doppelt eingestellt (188–208)', keys: ['F Moll', 'C# Moll', 'G Moll'],
    inst: ['hüpfendes Offbeat-Piano', 'kurze 808', 'Clap', 'schnelle Hats', 'Synth-Stabs'], snare: 'Clap auf 2 & 4 (nicht Half-Time!)',
    hats: 'schnelle 16tel, viel Bewegung', bass: 'kurze 808, oft mit kleinen Glides', arr: 'Kurze Loops, Rapper flowt „off-beat“ – Beat bleibt konstant',
    tip: 'Das Piano hüpft auf den Offbeats – spielen statt klicken.', refs: ['BabyTron', 'Veeze', 'Babyface Ray', 'Helluva (Prod.)'] },
  'Jerk': { fam: 'US', bpm: [145, 165], keys: ['C Dur', 'A Moll', 'E Moll'],
    inst: ['luftige Bells/Plucks', 'Trance-Synths', 'Jersey-Kicks', 'verzerrte 808', 'Vocal-Chops'], snare: 'Clap meist auf 2 & 4, Kick-Figuren im Jersey-Stil',
    hats: 'schnelle, dünne Hats', bass: 'verzerrte 808, kurz', arr: 'Sehr kurze Songs (1:30–2:30), schnelle Wechsel', tip: 'Hell, luftig, schnell – Lücken lassen, damit die Vocals fliegen.', refs: ['Xaviersobased', 'Nettspend', 'OsamaSon'] },
  'Memphis': { fam: 'US', bpm: [130, 145], keys: ['C# Moll', 'F Moll'],
    inst: ['Cowbell', 'Memphis-Vocal-Chops', 'Lo-Fi-Drums', 'Horror-Synths', '808'], snare: 'auf der 3 (Half-Time)',
    hats: '90s-Hats, leicht schmutzig', bass: 'dumpfe 808', arr: 'Loop-basiert, gechoppte Vocal-Samples', tip: 'Tape-Sättigung + Cowbell = sofort Memphis.', refs: ['Three 6 Mafia', 'Duke Deuce', 'Tommy Wright III'] },
  'Chicago Drill': { fam: 'US', bpm: [130, 140], keys: ['A Moll', 'F Moll'],
    inst: ['dunkles Piano', 'Strings', 'lange 808', 'Glocken', 'Chor'], snare: 'auf der 3 (Half-Time – fühlt sich wie 65–70 BPM an, Chicago-Style)',
    hats: 'Triolen und Rolls', bass: 'lange 808 ohne viele Slides', arr: 'Düsterer Loop, Hook repetitiv', tip: 'Chicago-Drill: langsamer und schwerer als UK-Drill.', refs: ['Chief Keef', 'King Von', 'Lil Durk'] },
  'NY Drill': { fam: 'US', bpm: [140, 145], keys: ['G Moll', 'D# Moll'],
    inst: ['Sliding 808', 'gechoppte Vocal-Samples', 'dunkle Pianos', 'Strings', 'Drill-Percs'], snare: 'auf der 3 + versetzte Snares (UK-Drill-Basis)',
    hats: 'Triolen-Hats mit Swing', bass: 'harte 808-Slides', arr: 'Aggressiver Aufbau, Adlibs als Element', tip: 'UK-Drill-Drums + amerikanische Energie.', refs: ['Pop Smoke', '808Melo (Prod.)', 'Fivio Foreign'] },
  'Sample Drill': { fam: 'US', bpm: [140, 148], keys: ['je nach Sample'],
    inst: ['gepitchtes R&B/Pop-Sample', 'Sliding 808', 'Drill-Hats', 'Jersey-Kick-Rolls'], snare: 'auf der 3 (Drill)',
    hats: 'Drill-Triolen', bass: '808-Slides', arr: 'Sample ist die Hook – Drums drumherum', tip: 'Bekanntes Sample schneller/höher pitchen und darüber droppen.', refs: ['Kay Flock', 'B-Lovee', 'Cash Cobain'] },
  'Jersey Club': { fam: 'US', bpm: [130, 140], keys: ['E Moll', 'B Moll'],
    inst: ['Kick-Rolls', 'Bed-Squeak', 'Vocal-Chops', '„Ha“-Vocal-Crash', 'Synth-Stabs', 'Clap'], snare: 'Clap auf 2 & 4',
    hats: 'wenig – die Kicks machen den Rhythmus', bass: 'kurz, auf den Kicks', arr: 'Typisch: 5-Kick-Triolen-Figur am Ende des Takts', tip: 'Das Kick-Pattern (bum-bum-bum-bumbum) ist der ganze Trick.', refs: ['Bandmanrill', 'Cookiee Kawaii', 'DJ Sliink'] },
  'West Coast': { fam: 'US', bpm: [88, 100], keys: ['A Moll', 'D Moll'],
    inst: ['G-Funk-Synth-Whine', 'Talkbox', 'funky Bass', 'Clap', 'Rhodes'], snare: 'Snare/Clap auf 2 & 4',
    hats: 'lockere 16tel', bass: 'Funk-Bassline (Moog)', arr: 'Laid-back, Loop mit kleinen Variationen', tip: 'Der hohe Sinus-Lead („Whine“) = sofort G-Funk.', refs: ['Dr. Dre', 'Snoop Dogg', 'Kendrick Lamar'] },
  'Ratchet': { fam: 'US', bpm: [95, 105], keys: ['A Moll', 'F Moll'],
    inst: ['minimaler Synth-Lead', 'Clap', '„Hey!“-Chants', 'bouncy 808', 'Finger-Snaps'], snare: 'Clap auf 2 & 4',
    hats: 'wenig, straight', bass: 'bouncy 808', arr: 'Sehr minimal, Party-Hook', tip: 'Weniger ist mehr: 3 Sounds + Chants (DJ-Mustard-Style).', refs: ['DJ Mustard', 'YG', 'Tyga'] },
  'Bay Area': { fam: 'US', bpm: [95, 105], keys: ['C Moll', 'G Moll'],
    inst: ['Slapper-Bass', 'schnelle Synths', 'Claps', 'Whistle', 'Hyphy-Chants'], snare: 'Clap auf 2 & 4',
    hats: 'schnelle, knackige Hats', bass: 'aggressiver „Slapper“-Bass', arr: 'Energisch, Party', tip: 'Harter Bass, Claps, Chants – Hyphy ist Energie.', refs: ['E-40', 'Too $hort', 'Larry June'] },
  'Boom Bap': { fam: 'US', bpm: [86, 94], keys: ['A Moll', 'D Moll', 'Eb Dur'],
    inst: ['Soul-/Jazz-Sample', 'staubige Drums', 'Vinyl-Crackle', 'Upright-Bass', 'Rhodes'], snare: 'auf 2 & 4 (nicht Half-Time)',
    hats: 'geswingte 8tel', bass: 'Upright oder Sub folgt dem Sample', arr: 'Sample-Loop, Scratches als Übergang', tip: 'Swing! Drums leicht hinter dem Takt.', refs: ['DJ Premier', 'J Dilla', 'Pete Rock'] },
  // ── FR / ES ───────────────────────────────────────────────────────────
  'Afro-Trap (FR)': { fam: 'FR/ES', bpm: [100, 112], keys: ['A Moll', 'D Moll', 'E Moll'],
    inst: ['Afro-Percs', 'Trap-Hats', '808', 'Gitarre/Kora', 'Marimba', 'Vocal-Chops'], snare: 'Afro-Rims synkopiert + Clap auf der 3 (Half-Time-Feel)',
    hats: 'Trap-Hats über Afro-Shaker', bass: '808 mit Afro-Rhythmus', arr: 'Hook-lastig, Stadion-Energie', tip: 'Afro-Groove unten, Trap-Hats oben – beides gleichzeitig.', refs: ['MHD', 'Niska', 'Tiakola', 'Naza'] },
  'French Drill': { fam: 'FR/ES', bpm: [140, 145], keys: ['F# Moll', 'C# Moll'],
    inst: ['melancholisches Piano', 'Sliding 808', 'Strings', 'Chor', 'Drill-Percs'], snare: 'auf der 3 + versetzte Drill-Snares',
    hats: 'Drill-Triolen', bass: '808-Slides', arr: 'Melancholisch-melodisch, Hook gesungen', tip: 'UK-Drill-Drums mit französischer Melancholie im Piano.', refs: ['Gazo', 'Ziak', 'Kerchak'] },
  'Morad-Style': { fam: 'FR/ES', bpm: [95, 105], keys: ['E Phrygisch-Dominant (Skala)', 'A Phrygisch (Skala)', 'D Moll'],
    inst: ['Flamenco-/Spanische Gitarre', 'Oud', 'Raï-Keys/Maghreb-Synth', 'Darbuka', 'Tabla', 'Autotune-Vocals', 'Reverb-Vocal-Chops'],
    snare: 'Clap auf der 3 (Half-Time) oder Dembow-artig', hats: 'sparsam, dafür Darbuka-Rolls', bass: '808 oder Sub, eher ruhig',
    arr: 'Melancholischer Loop, gesungene Hooks – Straßen-Rap mit nordafrikanischen (marokkanischen) Melodien, wie ihn Morad macht', tip: 'Phrygisch-dominante Tonleiter (Halbton-Schritt am Anfang) = sofort orientalischer Klang.',
    refs: ['Morad (Barcelona)', 'Beny Jr', 'Soolking', 'JUL'] },
  // ── ANDERE ────────────────────────────────────────────────────────────
  'Contemporary R&B': { fam: 'Andere', bpm: [65, 95], keys: ['Db Dur', 'Ab Dur', 'Bb Moll'],
    inst: ['Rhodes', 'Gitarre', 'weiche Pads', 'Finger-Snaps', 'Sub-Bass'], snare: 'auf 2 & 4 (oft Snaps/Rims)', hats: 'weiche 16tel',
    bass: 'warmer Sub', arr: 'Verse – Pre – Hook – Bridge', tip: 'Erweiterte Akkorde + viel Luft.', refs: ['Brent Faiyaz', 'SZA'] },
  'Deutschrap': { fam: 'Andere', bpm: [85, 150], keys: ['A Moll', 'C Moll', 'G Moll'],
    inst: ['Piano', '808', 'Strings', 'Vocal-Chops', 'Gitarre'], snare: 'je nach Stil: 2 & 4 oder auf der 3 (Half-Time)', hats: 'je nach Stil',
    bass: '808', arr: 'Hook-lastig', tip: 'Oft Mix aus Trap-Drums und Pop-Melodie.', refs: ['Luciano', 'Pashanim', 'Apache 207'] },
  'Lo-Fi': { fam: 'Andere', bpm: [70, 90], keys: ['F Dur', 'C Dur', 'E Moll'],
    inst: ['Jazz-Chords', 'Tape-Wobble', 'Rain-FX', 'Soft-Kick', 'Vinyl-Crackle'], snare: 'auf 2 & 4, weich', hats: 'geswingt',
    bass: 'weicher Sub', arr: 'Loop, kaum Wechsel', tip: 'Sättigung + Wobble + Swing.', refs: ['Nujabes', 'Jinsang'] },
  'Pop': { fam: 'Andere', bpm: [95, 125], keys: ['C Dur', 'G Dur', 'F Dur'],
    inst: ['Synth-Leads', 'Claps', 'Plucks', 'Akustikgitarre', 'Pads'], snare: 'auf 2 & 4', hats: '8tel', bass: 'Synth-Bass',
    arr: 'Verse – Pre – Chorus, Chorus nach < 1 Min.', tip: 'Die Hook muss nach 1x Hören sitzen.', refs: ['The Weeknd', 'Dua Lipa'] },
  'Phonk': { fam: 'Andere', bpm: [130, 150], keys: ['C# Moll', 'F Moll'],
    inst: ['Cowbell-Melodie', 'verzerrte 808', 'Memphis-Vocals', 'Drift-FX'], snare: 'auf der 3 (Half-Time)', hats: 'schnelle Hats',
    bass: 'stark verzerrte 808', arr: 'Cowbell-Riff als Hook', tip: 'Drift-Phonk: Cowbell + Distortion.', refs: ['Kordhell', 'DVRST'] },
  'Hyperpop': { fam: 'Andere', bpm: [140, 170], keys: ['B Dur', 'E Dur'],
    inst: ['Supersaws', 'gepitchte Vocals', 'Glitch-FX', 'verzerrte Drums'], snare: 'auf 2 & 4 oder Half-Time', hats: 'chaotisch',
    bass: 'übersteuert', arr: 'Abrupte Wechsel', tip: 'Alles „zu viel“ – mit Absicht.', refs: ['100 gecs', 'Charli XCX'] },
  'House': { fam: 'Andere', bpm: [120, 126], keys: ['A Moll', 'F Moll', 'C Dur'],
    inst: ['Four-on-the-floor-Kick', 'Offbeat-Hats', 'Piano-Stabs', 'Deep-Bass', 'Vocal-Chops'], snare: 'Clap auf 2 & 4',
    hats: 'offene Hat auf jedem Offbeat', bass: 'Bass auf den Offbeats', arr: '16er/32er-Blocks, Breakdown + Build-up + Drop', tip: 'Kick auf jeden Schlag, Clap 2 & 4, Hat auf „und“.', refs: ['Calvin Harris', 'Fred again..', 'Disclosure'] },
  'Indie House': { fam: 'Andere', bpm: [118, 124], keys: ['D Dur', 'B Moll', 'E Moll'],
    inst: ['Gitarren-Riff', 'warme Synths', 'Four-on-the-floor', 'gefilterte Vocals'], snare: 'Clap auf 2 & 4', hats: 'Offbeat-Hats',
    bass: 'melodischer Bass', arr: 'Songstruktur statt Club-Tool', tip: 'Gitarre + House-Groove.', refs: ['Jungle', 'Parcels'] },
  'Indie Rock': { fam: 'Andere', bpm: [110, 150], keys: ['E Dur', 'A Dur', 'D Dur'],
    inst: ['verzerrte Gitarre', 'Live-Drums', 'Bassgitarre', 'Tambourin', 'Gang-Vocals'], snare: 'auf 2 & 4', hats: 'Hi-Hat/Ride in 8teln',
    bass: 'Bassgitarre folgt dem Grundton', arr: 'Verse – Chorus – Bridge, lauter Schluss-Chorus', tip: 'Live einspielen, Fehler behalten.', refs: ['Arctic Monkeys', 'The Strokes'] },
};

// ---- production challenges ("Sample-/Sound-Challenge") --------------------
// One per order – short and doable, never more than one line.
const GENERIC_IDEAS = [
  'Nimm ein Geräusch aus deinem Alltag auf (Schlüssel, Tür, Tasse) und bau es als Percussion ein',
  'Baue nach 16 Takten einen Beat-Switch ein',
  'Nutze nur Stock-Plugins von FL Studio',
  'Leg ein Film- oder Interview-Zitat ins Intro',
  'Spiel die Hauptmelodie live mit dem Keyboard ein',
  'Benutze ein Vocal-Sample als Hook-Element',
  'Mach eine Stelle, an der alles außer einem Sound stoppt (Drop-Pause)',
];
export const IDEAS = {
  'UK Sample-Rap': ['Sample einen alten Soul-Song und chop ihn in 4–8 Stücke', 'Nimm ein Oldie- oder Film-Sample als Intro und lass es alleine laufen', 'Pitch ein Vocal-Sample hoch und nutz es als Hook', 'Baue den ganzen Beat um EIN auffälliges Sample herum'],
  'UK Rap': ['Sample einen alten Soul-Song und chop ihn', 'Leg einen gepitchten Vocal-Chop über die Hook', 'Beat-Switch nach dem 2. Part'],
  'UK Afroswing': ['Spiel die Shaker/Percs live ein, nicht klicken', 'Bau ein Gitarren- oder Kalimba-Riff als Hook-Melodie', 'Nutze einen Vocal-Chop als Antwort auf die Melodie'],
  'Afrobeats': ['Layer 4 Percussions mit je eigenem Rhythmus', 'Nutze ein Saxophon- oder Flöten-Riff', 'Nimm eine Talking-Drum- oder Conga-Figur auf'],
  'Amapiano': ['Programmier eine Log-Drum-Bassline mit Pitch-Slides', 'Baue einen langen Filter-Build über 16 Takte'],
  'Afro-Dancehall': ['Programmier ein sauberes Dembow-Pattern (3+3+2)', 'Füge einen Airhorn- oder Chant-Effekt im Drop ein'],
  'Dancehall': ['Baue einen Riddim, der ohne Melodie schon grooved', 'Nutze Skank-Gitarre oder Organ-Stabs auf den Offbeats',
    'Minimal-Riddim: fast nur Percussion (wie „Pepper Seed“ oder „Punnany“)', 'Baue 3 Sektionen, zwischen denen Instrumente rein- und rausfallen (Dub-Prinzip)',
    'Stop-Time: vor der Hook einen Takt komplett Stille', 'Gib deinem Riddim einen eigenen Namen – wie „Diwali“ oder „Sleng Teng“',
    'Nur digitale/Casio-artige Sounds wie beim „Sleng Teng“ (1985)', 'Eine Gitarren- oder Synth-Figur als Haken wie beim „Bam Bam“-Riddim'],
  'Dancehall-Trap': ['Kombiniere Trap-Hats mit einem Dancehall-Snare-Roll', 'Füge eine Sirene/Airhorn in der Hook ein'],
  'UK Drill': ['Die Melodie soll nur aus 808-Slides bestehen', 'Nutze einen Choir-Sound als Hauptmelodie'],
  'Atlanta Trap': ['Programmier Hi-Hat-Rolls in 3 verschiedenen Geschwindigkeiten', 'Nutze eine Flöte oder Glocke als Hauptmelodie'],
  'Dark Trap': ['Nutze einen Horror-Film-Sound oder Chor als Intro', 'Lass die 808 zwei Takte komplett alleine spielen'],
  'Melodic Trap': ['Nimm einen Gitarren-Loop (selbst gespielt oder Sample) als Basis'],
  'R&B Trap': ['Sample einen alten R&B-Song und pitch ihn runter', 'Nutze gepitchte Vocal-Chops als Melodie'],
  'Alternative R&B': ['Lass die Drums komplett weg und bau nur Atmosphäre', 'Nimm etwas mit dem Handy-Mikro auf und nutze die „schlechte“ Qualität bewusst'],
  '90s R&B': ['Programmier geswingte 16tel-Hats im New-Jack-Swing-Stil', 'Baue einen Key-Change in der letzten Hook'],
  'Sexy Drill': ['Sample einen bekannten Love-Song und leg Drill-Drums drunter'],
  'Sample Drill': ['Nimm ein bekanntes Pop-/R&B-Sample, pitch es hoch, Drill-Drums drunter'],
  'Rage': ['Schick einen Synth-Lead durch starke Distortion + Reverb'],
  'Plugg': ['Maximal 3 Elemente – nicht mehr'],
  'Pluggnb': ['Nutze Akkorde mit 7ern und 9ern im Plugg-Stil'],
  'Detroit': ['Spiel das Offbeat-Piano live ein'],
  'Jerk': ['Halte den Beat unter 2 Minuten und trotzdem mit 2 Wechseln'],
  'Memphis': ['Chop ein Vocal-Sample im Memphis-Stil (kurz, repetitiv)', 'Nutze eine Cowbell als Melodie'],
  'Jersey Club': ['Programmier die klassische 5-Kick-Figur am Taktende', 'Nutze einen Bed-Squeak oder ein lustiges Sample als Percussion'],
  'West Coast': ['Bau einen hohen Synth-Whine als Lead', 'Spiel eine funky Bassline'],
  'Boom Bap': ['Sample einen alten Jazz- oder Soul-Song', 'Swing die Drums (FL-Swing-Regler im Channel Rack)'],
  'Morad-Style': ['Spiel eine Melodie in phrygisch-dominant (orientalischer Klang)', 'Nutze eine spanische Gitarre oder Oud als Hauptinstrument', 'Baue einen Darbuka-Roll als Übergang ein'],
  'Afro-Trap (FR)': ['Kombiniere Afro-Shaker mit Trap-Hat-Rolls', 'Nutze eine Kora- oder Gitarren-Melodie'],
  'French Drill': ['Schreib eine melancholische Piano-Melodie in Moll'],
  'House': ['Baue einen Breakdown + Build-up + Drop', 'Nutze einen gechoppten Vocal als Hook'],
  'Indie House': ['Spiel ein Gitarren-Riff ein und leg es auf einen House-Groove'],
  'Indie Rock': ['Nimm etwas live auf (Gitarre, Stimme, Klatschen)'],
  'Reggaeton': ['Halte das Dembow-Pattern durchgehend und variiere nur die Melodie'],
  'UK Garage': ['Programmier einen 2-Step-Groove mit starkem Swing'],
  'Grime': ['Nur Square-Wave-Sounds benutzen'],
};
export const ideaFor = (genre) => {
  const own = IDEAS[genre] || [];
  const pool = own.length && Math.random() < 0.75 ? own : GENERIC_IDEAS;
  return pool[Math.floor(Math.random() * pool.length)];
};

// Genre names that changed (old saved orders/settings get migrated).
export const GENRE_RENAMES = { 'Trap': 'Atlanta Trap', 'Drill': 'Chicago Drill', 'R&B': 'Contemporary R&B', 'Maghreb-Urban': 'Morad-Style' };

// 🧱 Step-by-step blueprints ("so baust du ihn") for the core genres.
// Sources: own knowledge, cross-checked with production guides
// (Manuel & Marshall 2006 for dancehall; drill/jersey/amapiano/afroswing guides).
export const STEPS = {
  'UK Afroswing': [
    'Tempo 100–108 BPM, Moll (z. B. A- oder F#-Moll). Starte mit 4 Takten Akkorden auf Gitarre oder Keys – warm, nicht düster.',
    'Kick + Snare: Snare/Clap auf die 3 (Half-Time), dazu Rims im 3+3+2-Muster drumherum.',
    'Shaker in 16teln, dann Congas/Percs in die Lücken. Swing 10–20 % im Channel Rack oder Percs leicht neben das Raster schieben.',
    'Sub oder kurze 808 mit einer eigenen kleinen Melodie, die mit der Kick läuft.',
    'Takt 2 leicht variieren (ein Perc anders), alles als 8-Takt-Loop.',
    'Aufbau: 4 Takte Intro (nur Gitarre/Keys) → Hook 8 → Part 16 → Hook 8 → Part 16 → Hook. Vor jeder Hook 1 Takt ohne Drums.',
  ],
  'UK Rap': [
    'Sample oder Piano-Loop mit Seele suchen, in Edison/Slicex zuschneiden und auf ~140 BPM bringen.',
    'Snare auf die 3 (Half-Time), Kick sparsam – nicht jede Lücke füllen.',
    'Hats in 8teln, nur ab und zu ein Roll.',
    '808 auf den Grundton des Samples stimmen, sie folgt der Kick.',
    'Platz für die Bars: im Sample 1–4 kHz leicht absenken, wo die Stimme sitzt.',
    'Aufbau: 4–8 Takte Sample alleine → Drums droppen → Part 16 → Hook 8. Beat-Switch nach Part 2 ist beliebt.',
  ],
  'UK Sample-Rap': [
    'Sample aussuchen (Soul, Oldie, Filmmusik, Vocal) – Charakter geht vor Sauberkeit.',
    'In Slicex chopen, die besten 1–2 Takte als Loop, bei Bedarf pitchen.',
    'Drums wie im UK Rap: Snare auf die 3, simple Hats – das Sample führt.',
    '808 auf den Grundton des Samples, eher kurz.',
    'Einen Vocal-Chop aus dem Sample als wiederkehrenden Hook-Moment nutzen.',
    'Intro: Sample alleine (gern gefiltert), dann Drop mit allen Drums.',
  ],
  'UK Drill': [
    '140 BPM (138–144), Moll (F#- oder C#-Moll). Dunkle Melodie aus Piano, Strings oder Choir – 2–4 Akkorde.',
    'Snare: Takt 1 auf die 3, Takt 2 auf die 4. Leise Ghost-Snares (Velocity 40–50 %) dazwischen.',
    'Hats im 3+3+2-Muster, dazu Triolen-Rolls und bewusst kleine Pausen.',
    'Kick und 808 zusammen setzen; in der 808 Porta an, Slides meist eine kleine Terz oder Quarte, 2–3 Slides pro 4 Takte.',
    'Percs (Rim, Snaps) als Füller mit wenig Velocity.',
    'Aufbau: 8 Takte Intro → Hook 8 → Part 16. Das 808-Pattern in Hook und Part unterschiedlich machen.',
  ],
  'Afrobeats': [
    '100–112 BPM. Akkord- oder Riff-Loop auf Gitarre, Marimba oder Keys – gern hell.',
    'Kick synkopiert (nicht stur auf jeden Schlag), Rim/Clap auf „2-und“ und 4.',
    'Shaker in 16teln, offene Hat auf dem Offbeat.',
    '3–4 Percs (Conga, Talking Drum, Cowbell) – jede mit ihrem eigenen Rhythmus.',
    'Melodischer Bass, der mit der Kick Frage-Antwort spielt.',
    'Lange Grooves: Variation über Percs, die rein- und rausgehen, statt über große Drops.',
  ],
  'Amapiano': [
    '112 BPM (108–115), Kick 4-on-the-floor, 4-Takt-Pattern.',
    'Shaker in 16teln, ein zweiter Shaker leicht versetzt; offene Hat auf den Offbeats, Rim/Clap sparsam.',
    'Jazzige Piano-Akkorde (7er, 9er) plus weite Pads.',
    'Log Drum: gepitchter Bass-/Percussion-Sound mit Slides, synkopiert gespielt – das ist das Herz.',
    'Menschlich machen: Shaker-Velocity variieren, ab und zu einen Schlag weglassen.',
    'Lang aufbauen: alle 8–16 Takte ein neues Element oder ein Filter-Sweep.',
  ],
  'Dancehall': [
    '90–110 BPM. Dembow-Grundgerüst: Kick auf allen 4 Schlägen, Snare auf „1-a“ und „2-und“ (3+3+2).',
    'Rims und Percs statt vieler Hats.',
    'Tiefer Sub mit einer simplen Figur, die zur Kick passt.',
    'Ein Haken: Skank-Gitarre oder Organ auf den Offbeats oder ein Gitarren-/Synth-Riff wie beim „Bam Bam“-Riddim.',
    '2–3 Sektionen bauen, zwischen denen Instrumente rein- und rausfallen (Dub-Prinzip).',
    'Stop-Time: 1 Takt Stille vor der Hook. Gib dem Riddim einen Namen.',
  ],
  'Detroit': [
    '94–104 BPM (im FL oft doppelt: 188–208), Moll.',
    'Piano: kurze, hüpfende Figur auf den Offbeats – einspielen statt klicken.',
    'Clap/Snare auf 2 & 4, trocken und weit vorne im Mix.',
    'Hats in schnellen 16teln mit Triolen-Rolls und Velocity-Unterschieden – die machen den Bounce.',
    'Kurze 808 mit kleinen Glides, folgt der Kick.',
    'Kurzer Loop, der konstant bleibt – der Rapper flowt „off-beat“ drüber.',
  ],
  'Jerk': [
    '~150–160 BPM, helle Tonart (Dur oder helles Moll).',
    'Luftiger Loop aus Bells, Plucks oder Trance-Synth – viel Platz lassen.',
    'Kick-Figuren im Jersey-Stil, Clap/Snare auf 2 & 4 (mit Rim gelayert).',
    'Dünne, schnelle Hats.',
    'Kurze, verzerrte 808.',
    'Kurz halten (1:30–2:30), schnelle Wechsel, Vocal-Chops als Akzente.',
  ],
  'Jersey Club': [
    '140 BPM (130–140).',
    'Kick-Grundmuster auf den 16tel-Steps 1, 5, 9, 12 und 15, dann die Triolen-Figur „bum-bum-bum-bumbum“ am Taktende.',
    'Clap auf 2 & 4, Bed-Squeak (aus Trillvilles „Some Cut“, 2004) auf oder zwischen den Kicks.',
    'Vocal-Chop, der mit den Kicks stottert, und ein „Ha“-Crash als Akzent.',
    'Kaum Melodie (ein Akkord-Stab), kurzer Bass.',
    'Alle 4–8 Takte variieren; für den Rapper Chops oder Kicks rausnehmen.',
  ],
  'Atlanta Trap': [
    '130–150 BPM (oft 140), Moll. 8-Takt-Melodie auf Bells, Flöte oder Piano.',
    'Snare/Clap auf die 3 (Half-Time).',
    'Hats in 8teln/16teln mit 1/32- und Triolen-Rolls.',
    'Lange, gestimmte 808 mit Glides, folgt der Kick.',
    'Vor der Hook kurz alles muten, dann droppen.',
    'Aufbau: 8 Takte Intro (Melodie alleine) → Hook 8 → Part 16.',
  ],
  'R&B Trap': [
    '130–150 BPM (Half-Time-Feel). R&B-Akkorde (Maj7, Moll9) auf Rhodes oder Pads.',
    'Snare/Snap auf die 3, weich.',
    'Sanfte Hat-Rolls, nichts Aggressives.',
    'Weiche 808, die den Akkorden folgt.',
    'Gepitchte Vocal-Chops als Füller zwischen den Zeilen.',
    'Aufbau: Verse – Hook – Verse – Bridge – Hook.',
  ],
  'Afro-Trap (FR)': [
    '100–112 BPM. Afro-Percussion-Loop (Shaker, Congas) als Fundament.',
    'Gitarren-, Kora- oder Marimba-Riff als Hook-Melodie.',
    'Clap auf der 3 (Half-Time-Feel), Rims synkopiert.',
    'Trap-Hats darüber legen – Afro unten, Trap oben.',
    '808 im Afro-Rhythmus.',
    'Hook-lastig mit Stadion-Energie – die Hook kommt oft zuerst.',
  ],
  'Morad-Style': [
    '95–105 BPM. Melodie in E-phrygisch-dominant (E–F–G#–A–H–C–D) = sofort orientalisch.',
    'Spanische Gitarre oder Oud als melancholischer Loop.',
    'Clap auf die 3 oder Dembow-artig; Darbuka-Rolls statt vieler Hats.',
    'Ruhiger Sub oder 808.',
    'Reverb-Vocal-Chops und viel Platz für eine gesungene Autotune-Hook.',
    'Den Loop simpel halten – die Stimme trägt.',
  ],
};
for (const [k, v] of Object.entries(STEPS)) if (GENRES[k]) GENRES[k].steps = v;
