// Who the customers are: names, a catchphrase only *they* use, random
// (useless) facts they drop into messages, and the rough sound they like.
//
// Per customer (index i within the archetype):
//   sig   = sigs[i]                 – their own catchphrase (unique)
//   facts = facts[2i], facts[2i+1]  – dropped in ~half of their messages
//   likes = 2 genres from `likes`   – they mostly order in that direction
// `factTpl` turns a fact into a sentence ({first} = their name).
// Pensioners and kids keep ordinary names on purpose.

export const PEOPLE = {
  chaya: {
    names: ['Shanice Velvet|f', 'Destinee Lamour|f', 'Chardonnay Bling|f', 'Mercedez Juicy|f', 'Porsha Honeydrip|f', 'Tiffany Twerkowski|f',
      'Jaqueline Sugarbabe|f', 'Chantal No.5|f', 'Lavinia Peachez|f', 'Rihannah Cashflow|f', 'Dolores Diamondz|f', 'Kimberly Kaviar|f'],
    sigs: ['mwah mwah mwah 💋', 'periodt pooh 💅', 'it’s giving ✨', 'no crumbs 🍞', 'ich bin literally obsessed', 'sheesh babe 😮‍💨',
      'ok aber slay tho', 'bestieee 🫶', 'ich schrei 😭', 'main character energy 👑', 'lowkey highkey 🤭', 'ate and left no crumbs 🍽️'],
    facts: ['ich hab einen fetten arsch 🍑', 'mein hund heißt Gucci und trägt Prada', 'ich hab 47 paar sneaker und trag nur 2', 'ich war fast bei Love Island',
      'meine wimpern kosten mehr als deine miete', 'ich trink nur rosé mit eiswürfeln', 'mein ex fährt golf 3 lol', 'mein BBL hat einen eigenen insta account',
      'ich esse nur sushi und chicken nuggets', 'ich hab 3 handys, eins nur für selfies', 'ich kann twerken und gleichzeitig abwaschen', 'ich bin im solarium eingeschlafen, 2 mal',
      'mein sternzeichen ist löwe, das erklärt alles', 'meine nägel sind so lang, ich tipp mit den knöcheln', 'ich hab heute schon 3 mal geduscht, für den glow',
      'ich hab ein foto mit Capital Bra (glaub ich)', 'ich trag nur leopard', 'ich hab mein auto nach mir selbst benannt', 'mein lieblingsessen ist döner ohne alles',
      'ich hab einen chihuahua namens Chanel', 'ich brauch 2 stunden fürs make-up und 5 minuten für den rest', 'ich hab noch nie ein buch gelesen und bin stolz drauf',
      'ich hab ein tattoo von meinem eigenen namen', 'ich hab einen sugar daddy, er heißt Dieter'],
    likes: ['R&B', 'Afrobeats', 'Dancehall', 'Pop', 'Jersey Club', 'Trap'],
    factTpl: 'ps: ich bin {first} und {fact}',
  },
  rentner: {
    sigs: ['Jaja, so ist das.', 'Grüß Gott und Glück auf!', 'Freude, Freude, Freude!', 'Tschüssikowski!', 'Na bitte, geht doch.', 'Herrje, die Technik!',
      'Gott zum Gruße.', 'Mahlzeit!', 'Halleluja 🙏', 'Servus, Kaiser!', 'Wunderbar, wunderbar.', 'Heiliger Bimbam!'],
    facts: ['Ich sammle Porzellanengel, 312 Stück.', 'Mein Wellensittich heißt Herr Müller.', 'Ich war 1971 beim Grand Prix im Publikum.', 'Ich mache jeden Tag 5 Kniebeugen. Manchmal 4.',
      'Mein Enkel hat mir TikTok installiert, ich weiß nicht, wie man es ausschaltet.', 'Ich habe 40 Jahre bei der Post gearbeitet.', 'Ich backe den besten Gugelhupf im Bezirk.',
      'Mein Gebiss heißt Günther.', 'Ich gehe jeden Mittwoch zur Wassergymnastik.', 'Ich habe Udo Jürgens einmal die Hand geschüttelt.', 'Ich schaue jeden Tag Rosamunde Pilcher.',
      'Ich füttere im Park die Tauben, alle haben Namen.', 'Das Handy ist sehr klein geschrieben.', 'Mein Mann schnarcht wie ein Traktor.', 'Ich trinke jeden Abend ein Stamperl Eierlikör.',
      'Ich hatte 1983 vier Richtige im Lotto.', 'Ich kann noch Steno.', 'Mein Garten hat mehr Gartenzwerge als Blumen.', 'Ich habe Angst vor Staubsaugerrobotern.',
      'Ich spiele Bingo und gewinne nie.', 'Ich habe 14 Enkel und merke mir 9 Namen.', 'Mein Hut ist älter als Sie.', 'Ich lese jeden Tag die Todesanzeigen, zur Sicherheit.',
      'Ich habe gestern „Alexa“ angeschrien.'],
    likes: ['Pop', 'Lo-Fi', 'R&B', 'Boom Bap'],
    factTpl: 'P.S.: {fact}',
  },
  kid: {
    sigs: ['aura +1000 🗿', 'sigma sigma', 'GG mama', 'lol xD', 'bruh', 'no cap fr', 'skibidi (sorry)', 'juhuuu', 'sheeesh', 'lets goooo', 'easy peasy', 'ok tschau'],
    facts: ['ich hab einen wackelzahn', 'ich kann rülpsen und dabei das alphabet sagen', 'mein hamster heißt Krümel und ist fett', 'ich bin in mathe der beste (außer Lukas)',
      'ich hab heute pommes zum frühstück gegessen', 'ich kann einen salto (auf dem trampolin)', 'mein papa ist stärker als deiner', 'ich hab einen stein gefunden der aussieht wie ein dino',
      'ich darf nur 1 stunde handy', 'ich hab 12 pokemon karten und eine glitzert', 'ich will youtuber werden', 'meine schwester ist nervig', 'ich hab eine lego stadt gebaut',
      'ich esse nur nudeln ohne soße', 'ich kann mit den ohren wackeln', 'ich hab einen fast roten gürtel in karate', 'meine lehrerin heißt Frau Brösel',
      'ich hab einen zauberwürfel in 3 tagen gelöst', 'ich hab angst vor clowns', 'ich hab heute einen regenwurm gerettet', 'mein opa kann die zunge rollen', 'ich sammle kronkorken',
      'ich hab einen furz im lift gelassen und es war nicht ich', 'ich kann schon bis 1000 zählen'],
    likes: ['Hyperpop', 'Phonk', 'Pop', 'Trap', 'Jersey Club'],
    factTpl: 'ich bin {first} und {fact}',
  },
  gamer: {
    names: ['milfhunter|m', 'xX_Sn1p3rG0d_Xx|m', 'N00bSlayer2009|m', 'RageQuitRalf|m', 'ChunkyChris_TTV|m', 'KeyboardKrieger420|m', 'LagLord_Lutz|m', 'MonsterEnergyMike|m'],
    sigs: ['gg ez no re', 'sheeesh, cracked', 'ratio + L', 'touch grass (ich nicht)', '1v1 mich bro', 'pog champ', 'clutch or kick', 'lag war schuld'],
    facts: ['ich hab seit 3 tagen nicht geduscht, grind', 'mein stuhl kostet mehr als mein bett', 'ich hab 12 monster dosen im zimmer stehen, leer', 'ich wohn noch bei mama und das ist ok',
      'ich hab mal gegen einen pro gespielt (verloren)', 'ich ess cheetos mit stäbchen wegen tastatur', 'meine freundin wohnt in kanada (ja echt)', 'ich hab 7000 stunden in CS',
      'mein headset hat RGB und ich auch', 'ich hab einen discord server mit 4 leuten', 'ich hab den controller mal gegen die wand geworfen', 'mein zimmer riecht nach doritos und erfolg',
      'ich schlaf tagsüber wie ein vampir', 'mein lieblingsessen ist tiefkühlpizza, halb warm', 'ich bin fortnite champion (in meinem kopf)', 'ich hab mal 20 minuten vom klo gestreamt'],
    likes: ['Phonk', 'Hyperpop', 'Trap', 'Drill'],
    factTpl: 'btw ich bin {first} und {fact}',
    fullName: true,
  },
  rapper: {
    names: ['Lil Kanalratte|m', 'Big Mo Moneten|m', 'Kid Kanone|m', 'Yung Döner|m', 'MC Mietschulden|m', 'Rolex-Ronny|m', 'Beton-Bernd|m', 'Gold-Gregor|m', 'Sniper Sascha|m', 'Blocklord Benno|m'],
    sigs: ['Wallah krise 💯', 'Ehrenwort auf Mama.', 'Bratan, versteh mich.', 'Hunnis zählen, nicht Freunde.', 'Straße ist Schule.', 'Kopf hoch, Kette auch.',
      'Wir sind die Echten.', 'Von 0 auf Benz.', 'Kein Stress, nur Press.', 'Block bleibt Block.'],
    facts: ['ich hab meinen ersten Beat auf dem Nokia gemacht', 'meine Kette ist aus Gold (vergoldet)', 'ich hab 2 Hunde, beide heißen Money', 'ich trinke nur Capri-Sonne',
      'meine Mama hört meine Songs und weint', 'ich trag nie Socken', 'ich hab mehr Streams als mein Vermieter Geduld', 'ich hab einen Döner als Tattoo',
      'ich schreib Texte nur im Auto', 'ich hab 3 Tage im Studio geschlafen', 'ich mach 200 Liegestütze am Tag (sagen wir 20)', 'mein Lieblingsessen ist Mamas Sarma',
      'ich hab eine Gucci-Tasche vom Basar', 'mein Kater heißt Pablo', 'ich hab den Führerschein 4 mal gemacht', 'ich trage Sonnenbrille auch nachts',
      'ich hab meinen Nachbarn schon 3 mal geweckt, sorry', 'ich hab mein erstes Mic bei Willhaben gekauft', 'ich kann nicht schwimmen, aber flowen', 'ich hab meinen Cousin gedisst und bereue nix'],
    likes: ['Drill', 'Trap', 'Deutschrap', 'Boom Bap'],
    factTpl: 'Nebenbei: ich bin {first} und {fact}.',
    fullName: true,
  },
  fitness: {
    names: ['Protein-Paul|m', 'Gainz-Gabriel|m', 'Max Muskelkater|m', 'Chad Brenner|m', 'Kevin Kreatin|m', 'Sixpack-Siggi|m', 'Bulk-Basti|m', 'Coach Kerstin Kniebeuge|f'],
    sigs: ['Light weight, baby! 💪', 'Pump it up!', 'No pain, no Gainz.', 'Ab ins Eisbad 🧊', 'Discipline equals freedom.', 'Einer geht noch!', 'Proteinshake, prost 🥤', 'Beast mode on.'],
    facts: ['ich esse 12 Eier am Tag', 'ich hab meinen Bizeps „Bruce“ getauft', 'ich trainiere auch am Heiligabend', 'ich hab seit 2019 kein Brot gegessen',
      'ich spreche mit meinen Muskeln', 'mein Kühlschrank ist nur Hähnchen', 'ich hab ein Tattoo von einer Hantel', 'ich hab beim Beinpressen geweint (vor Glück)',
      'ich trage Tanktops im Winter', 'ich hab einen Spiegel im Auto nur für Pump-Checks', 'ich zähle Kalorien im Schlaf', 'ich hab 3 Gym-Mitgliedschaften',
      'meine Freundin sagt, ich rieche nach Pre-Workout', 'ich hab mal ein Auto angeschoben, aus Spaß', 'ich lauf jeden Morgen 10 km (zum Bäcker)', 'ich hab meinen Hund auf Bulk gesetzt'],
    likes: ['Phonk', 'Trap', 'Drill', 'Hyperpop', 'Deutschrap'],
    factTpl: 'Fun Fact: Ich bin {first} und {fact}.',
    fullName: true,
  },
  crypto: {
    sigs: ['WAGMI fam 🚀', 'wen lambo?', 'buy the dip, bro', 'Diamond hands only 💎🙌', 'number go up 📈', 'ser, this is a Wendy’s', 'LFG!!!'],
    facts: ['ich hab mein Auto gegen ein Affen-JPEG getauscht', 'ich hab 3 Wallets und weiß kein Passwort mehr', 'ich trage nur Hoodies mit Bitcoin drauf', 'ich hab 2017 alles verkauft, großer Fehler',
      'ich rede mit ChatGPT über Charts', 'ich hab einen Hund namens Doge (natürlich)', 'ich wohn im Tiny House, aber bald Lambo', 'ich hab Laseraugen als Profilbild',
      'ich hab mal 40k verloren und bin trotzdem bullish', 'ich schlafe mit dem Chart auf dem Handy', 'meine Mama glaubt, ich bin Banker', 'ich hab mein Zimmer „Trading Floor“ getauft',
      'ich hab ein NFT von meinem eigenen Gesicht', 'ich trage nur Crocs'],
    likes: ['Trap', 'Hyperpop', 'Pop', 'Phonk'],
    factTpl: 'btw ich bin {first} und {fact}',
    fullName: true,
  },
  grantler: {
    names: ['Ferdl Grantnig|m', 'Poldi Wurschtler|m', 'Hansi Heurigenhuber|m', 'Pepi Pfusch|m', 'Mitzi Melange|f', 'Gustl Gemeindebau|m', 'Resi Radler|f', 'Schurli Schmäh|m'],
    sigs: ['Oida, eh kloa.', 'Des geht si ned aus.', 'Na servas, Kaiser!', 'Wurscht, gemma.', 'I sog’s da glei.', 'Geh bitte.', 'A so a Schas.', 'Passt eh, Burschi.'],
    facts: ['i hob 30 Joa bei da MA 48 goabeit', 'mei Hund hasst an Briaftroga', 'i trink an Spritzer zum Frühstück', 'i schimpf über ois, oba i wöhl nie',
      'mei Nochbar grüßt ned, i a ned', 'i kenn jede Würstlbude in Wien', 'i hob an Schrebergartn mit Griller', 'i hob 1985 fost an Hattrick gschossn',
      'i fohr seit 40 Joa mit da 13A', 'mei Oide sogt, i bin z’grantig – stimmt ned!', 'i hob a Sammlung vo Bierdeckln', 'i geh nur ins Kaffeehaus zum Zeitunglesn',
      'i hob a Autogramm vom Falco', 'i wart seit 1998 auf die Bim', 'i hob zwa linke Händ, oba a guats Herz', 'i ess jeden Sunntag a Schnitzl, ohne Ausnahm'],
    likes: ['Boom Bap', 'Deutschrap', 'Lo-Fi'],
    factTpl: 'Übrigens, i bin da {first} und {fact}.',
  },
  mama: {
    names: ['Uschi Glitzerstein|f', 'Petra Prosecco|f', 'Mandy Mamablog|f', 'Claudia Clean-Eating|f', 'Birgit Basteltante|f', 'Tanja Thermomix|f', 'Karin Kaffeeklatsch|f', 'Andrea Aperol|f'],
    sigs: ['Hach, herrlich 🥰', 'Prösterchen 🥂', 'Namaste, Mädels!', '#momlife 💕', 'Einfach nur wow 😍', 'Na, du Süßer? 😅', 'Bussi Baba 😘', 'Läuft bei uns! 🙌'],
    facts: ['ich hab 400 Pinterest-Boards', 'mein Thermomix heißt Helmut', 'ich mach jeden Tag Yoga und bin trotzdem gestresst', 'ich hab die Kinder nach Serienfiguren benannt',
      'ich trinke Aperol auch im Winter', 'ich bastel Deko aus Klopapierrollen', 'ich ändere meinen WhatsApp-Status 5 Mal am Tag', 'mein Mann Uwe kann nicht tanzen, gar nicht',
      'ich hab einen Mama-Blog mit 43 Followern', 'ich backe glutenfrei, schmeckt nur mir', 'ich hab 3 Katzen und einen Mann, der allergisch ist', 'ich schau heimlich den Bachelor',
      'ich hab für diese Nachricht Zumba geschwänzt', 'ich trag Leggings zu jedem Anlass', 'ich hab Ohrringe in Avocado-Form', 'ich organisiere den Elternabend seit 7 Jahren'],
    likes: ['Pop', 'Dancehall', 'Afrobeats', 'R&B'],
    factTpl: 'PS: Ich bin die {first} und {fact} 😅',
  },
  eso: {
    sigs: ['Alles ist Schwingung ✨', 'Om mani padme hum 🕉️', 'Vertrau dem Mond 🌙', 'Atme ein, atme aus 🌬️', 'Die Sterne lügen nicht ⭐', 'Liebe ist die Antwort 💗', 'Erdung, meine Lieben 🌳'],
    facts: ['ich rede mit meinen Pflanzen und sie antworten', 'ich war in einem früheren Leben eine Katze in Ägypten', 'ich lade meine Kristalle im Vollmond auf',
      'ich esse nur, was die Sonne gesehen hat', 'ich hab einen Traumfänger überm Bett und einen im Auto', 'mein Aszendent ist an allem schuld', 'ich trinke Mondwasser',
      'ich hab einen Salzlampenladen', 'ich umarme jeden Morgen einen Baum', 'ich höre Walgesänge beim Einschlafen', 'meine Aura ist lila (fotografiert!)',
      'ich reise nur, wenn Merkur direkt ist', 'ich hab einen Schamanen auf Instagram', 'meine Katze ist meine spirituelle Lehrerin'],
    likes: ['Lo-Fi', 'Afrobeats', 'R&B'],
    factTpl: 'Übrigens: Ich bin {first} und {fact} 🌙',
    fullName: true,
  },
  business: {
    sigs: ['Let’s circle back.', 'Win-win-win.', 'Mega spannend!', 'Zahlen lügen nicht.', 'Out of the box, bitte.', 'Wir denken das groß.'],
    facts: ['ich hab heute 14 Meetings, das hier ist Nummer 9', 'mein LinkedIn hat mehr Endorsements als ich Freunde', 'ich trinke 6 Espressi vor 10 Uhr', 'ich hab ein Stehpult und stehe nie',
      'mein Hund heißt „Asset“', 'ich lese nur Bücher mit „Mindset“ im Titel', 'ich hab eine PowerPoint über meine Hochzeit gemacht', 'ich schreibe E-Mails um 5 Uhr früh, aus Prinzip',
      'ich spiele Golf, aber nur fürs Networking', 'ich hab einen Podcast mit 2 Folgen', 'ich sage „Synergie“ 40 Mal am Tag', 'ich hab den Firmenlauf gewonnen (Kategorie Management)'],
    likes: ['Pop', 'Afrobeats', 'Trap'],
    factTpl: 'Fun Fact: {fact}.',
  },
  hipster: {
    sigs: ['Hmm, eher Nische.', 'Ganz ehrlich: analog > digital.', 'Kennst du eh nicht.', 'Warm und körnig, bitte.', 'Slow living, slow music.', 'Bio ist Pflicht.'],
    facts: ['ich hab keinen Fernseher, nur einen Plattenspieler', 'ich fahr ein Rennrad ohne Gänge', 'ich hab meinen Bart nach Hemingway benannt', 'ich röste meinen Kaffee im Hinterhof',
      'ich hab 3 Jutebeutel und nutze keinen', 'ich schreib Tagebuch mit Füller', 'mein Sauerteig heißt Gisela', 'ich hör Vinyl nur in Mono',
      'ich trink Hafermilch, aber nur Barista-Edition', 'ich hab einen Polaroid-Account', 'ich wohn in einem Altbau ohne Heizung, bewusst', 'ich hab ein Tattoo von einem Farn'],
    likes: ['Lo-Fi', 'Boom Bap', 'R&B'],
    factTpl: 'übrigens: ich bin {first} und {fact}',
  },
  weird: {
    names: ['Burtram Krötenfreund|m', 'Gunnar Gurkenkönig|m', 'Dietlinde Dachboden|f', 'Ottokar Ohrwurm|m', 'Wilma Wackelpudding|f', 'Eberhard Eierlöffel|m', 'Hilde Heizdecke|f'],
    sigs: ['Schildkröten sind die Zukunft 🐢', 'Gurke ist Leben 🥒', 'Psst… hörst du das auch?', 'Mmm, knusprig.', 'Wackel, wackel 🍮', 'Eier sind rund, das Leben auch 🥚', 'Kuschelig bleiben 🔥'],
    facts: ['ich mag Schildkröten', 'ich hab 212 Gurkengläser im Keller', 'ich wohne freiwillig auf dem Dachboden meiner Mama', 'ich summe seit 1994 dasselbe Lied',
      'ich esse Wackelpudding mit der Gabel', 'ich sammle Eierlöffel aus Hotels', 'ich schlafe mit 3 Heizdecken, auch im Sommer', 'meine Schildkröte heißt Gerhard und ist 60',
      'ich rede mit Gurken, bevor ich sie esse', 'ich hab einen Staubsauger adoptiert', 'ich zähle Treppenstufen, immer', 'ich kann mit den Zehen klatschen',
      'ich trage nur Socken mit Enten drauf', 'ich hab eine Taube gezähmt, sie heißt Karl'],
    likes: ['Lo-Fi', 'Hyperpop', 'Jersey Club', 'Dancehall', 'Boom Bap', 'Phonk'],
    factTpl: 'ich bin {first} und {fact}.',
  },
};
